### ISSUE TITLE
Use a configuration first method (modifiers and states) for Title

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1003]
Relates directly back to #273

**Comment by mcoker** [comment]
I'm inclined to leave this one as-is. We could write 2 vars for line-height and 2 vars for font-weight, then reference those 2 vars in the modifiers instead of having a unique line-height and font-weight var per modifier, but this seems like something a person might want more granular customization of than that. What do you think @mattnolting @christiemolloy?

**Comment by christiemolloy** [comment]
Maybe keep the variables in the head as is, so that a person can still customize them. But in the body I think you could group the modifiers that share line height and font weight. That seems consistent with the updates we've been making. 

But either way is good honestly.

**Comment by mcoker** [comment]
@christiemolloy I ran this by @mceledonia and he said just group 'em for this and the pf-c-content titles. woot!

**Comment by mcoker** [comment]
@christiemolloy I'm just going to leave this one since we haven't decided what we're going to do re: combining vars. Does it look like there is anything else to fix to you with this component? If not feel free to close it out.

**Comment by christiemolloy** [comment]
I don't see anything else. Closing the issue
