### ISSUE TITLE
Data Table: Refine visuals for column headers when sortable columns are supported

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1046]
Current examples in Table component shown the following implementation for sortable columns:

![screen shot 2018-12-03 at 11 25 08 am](https://user-images.githubusercontent.com/6619860/49386764-43815980-f6ee-11e8-8d8d-f8c368544528.png)

Questions include:

* What is proper direction of the caret to indicate sort direction when a row is selected?
* What icon should we use (and what color value, hover state, etc) to indicate that a column is sortable?

**Comment by mcarrano** [comment]
@gdoyle1 here are links to the current implementations of Table for your reference: 

PF Core CSS: https://pf-next.netlify.com/components/Table/examples/
PF React: https://821-pr-patternfly-react-patternfly.surge.sh/patternfly-4/components/table

Note that the React implementation has not yet been merged.

**Comment by gdoyle1** [comment]
@mcarrano Here's a prototype of how I expect the sort function to work ([InVision project](https://redhat.invisionapp.com/share/THPN2PDDM9C)).

The summary in writing: Column headers are now styled with a semi bold weight instead of regular. A column header is sortable if it has a hover state. The hover state would look very close to dropdown's hover state. That column header's line would become bold and gray when hovered over indicating that it is sortable. Upon select, the column header would enter focus state and sort the items from top-to-bottom (angle would be pointing upwards). The bold line underneath the column header and the angle icon would be blue. If the user clicks off of the column header, the focus state would disappear. If the column header or angle icon were selected again, the angle would point downwards and sort the items bottom-to-top. If the column header or angle icon were selected a third time, the column header and the list of items would return to it's original state, unsorted.

Let me know what you think!

**Comment by mcarrano** [comment]
For the most part I think this works. Only question is the last statement - revert to "unsorted" on the 3rd click. The problem with this is what is I really wanted to toggle the sort direction back. Hard to know what the user intent is here. Not sure we need a way to get to "unsorted". In most tables I see, there is usually a default sort and then I can change to something else by clicking the header. So the table is always sorted by something. Does that make sense?

**Comment by gdoyle1** [comment]
@mcarrano That makes sense! I guess if there's no use case that "revert to unsorted table" would cover then there's no sense of adding it.

**Comment by gdoyle1** [comment]
@mcarrano I removed the ability to revert to an unsorted table and added some more screens for another sortable column within the table [here](https://redhat.invisionapp.com/share/THPN2PDDM9C). Let me know if I need to change anything!

**Comment by mcarrano** [comment]
Yes, I think this makes sense @gdoyle1 . So if I understand this correctly, columns that are sortable but not currently selected will get a hover state. That works for me. @kybaker amd @mceledonia does this work for you?

Are you assuming that the focus state is based on the browser or is this a custom focus appearance that we are enforcing. If we are all good with this from a design perspective, we should float this with the development team to make sure they don't have issues. Tables are always tricky because we rely on 3rd party components.

**Comment by gdoyle1** [comment]
@mcarrano "Columns that are sortable but not currently selected will get a hover state" - Yes that is correct!

I believe the focus state is browser based for other components so I would assume it would act the same until we enforce a universal focus state (if we do that).

**Comment by gdoyle1** [comment]
All final examples of these can be found in this [Sketch File](https://drive.google.com/open?id=1RbOmDbxp-rkJgJ-rklhhIyppHSbMC3nl).

**Comment by gdoyle1** [comment]
Not sure if we want to revisit this based on the comments during the demo - I changed the design a bit and made the column headers that are sortable blue so they are easily seen when scanning a page. The rest of it works the same. https://redhat.invisionapp.com/share/THPN2PDDM9C Let me know what you think @mcarrano

**Comment by mcarrano** [comment]
@jgiardino while I do this this solves the problem, I'm not sure it's better than what was already implemented (an icon to the right of the label). So I take it that the current sorted column would be blue, also but with the additional underline? @kybaker @mceledonia what do you think? I don't feel that strongly either way.

**Comment by mcarrano** [comment]
Looks great @gdoyle1 . I think this is ready to hand off to CSS.

**Comment by mcoker** [comment]
resolved in https://github.com/patternfly/patternfly-next/pull/1067
