### ISSUE TITLE
Content Component Audit

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1081]
- Should the unordered list and ordered list exist inside of the list component instead of content?

- Should we consider breaking up headings/body text examples like http://patternfly-react.surge.sh/patternfly-4/components/text/ ? Its a lot more comprehendible .

**Comment by mcarrano** [comment]
@christiemolloy I agree that the React page is much more comprehensible and that the list examples logically belong in the List component.  Beyond that, I haven't given this much intention because I'm not totally clear what this component is for. Is it just to demonstrate comment text styling? Seems like the React version includes a more comprehensive set of body text styles. Thoughts?

**Comment by christiemolloy** [comment]
@mcarrano I agree. @LHinson @rachael-phillips do you have any suggestions?

**Comment by rachael-phillips** [comment]
Hi @christiemolloy and @mcarrano who is the designer for list component?

**Comment by christiemolloy** [comment]
closing this issue after discussion with @mcoker clarifying the issue
