### ISSUE TITLE
Tooltip 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#113]
The tooltip component requires the following: 
CSS to address update visuals and address technical comments seen on [current open PR](https://github.com/patternfly/patternfly-next/pull/442)

**Comment by sjcox-rh** [comment]
Visuals for tooltip. 

Two variations shown  - on hover and on click.

Please keep in mind to various placements of tooltips when implementing - on right, on left, on top, on bottom.

<img width="913" alt="screen shot 2018-06-12 at 1 59 34 am" src="https://user-images.githubusercontent.com/16257540/41272863-e926e276-6de4-11e8-8cad-b4dec58e6f1f.png">

Please review!

**Comment by christianvogt** [comment]
[PopperJS](https://popper.js.org/) is a very powerful placement library for popovers. It is used to position both the popover box and the arrow. The only stipulation when used for inclusion of arrow placement is that the arrow must be a separate HTML tag and not some pseudo element.

For example:
```html
<div class="pf-c-tooltip">
    <div class="pf-c-tooltip__arrow"></div>
    <div class="pf-c-tooltip__content">Tooltip content here.</div>
</div>
```

**Comment by sjcox-rh** [comment]
Update to visuals:

Separating out tooltip and popover to two separate components.

<img width="374" alt="screen shot 2018-06-12 at 10 15 46 am" src="https://user-images.githubusercontent.com/16257540/41295937-bde79dc2-6e29-11e8-89f2-3ab9cdafbbe2.png"><img width="376" alt="screen shot 2018-06-12 at 10 15 58 am" src="https://user-images.githubusercontent.com/16257540/41295942-c161f556-6e29-11e8-8c32-e9e330ed4e7b.png">

Please keep in mind to various placements of tooltips when implementing - on right, on left, on top, on bottom.

**Comment by trahman73** [comment]
For implementation into Ansible Tower, we feel that 32px padding is very large in relationship to the icon that will trigger the tooltip itself. We also feel the the white background of the tooltips do not provide any contrast against the application even with a drop shadow.

Example of size and background issue:
![image](https://user-images.githubusercontent.com/13351591/42843917-841bdcf8-89df-11e8-91e8-0ab2e147b839.png)

We are proposing a 16px padding tooltip with a dark background (exact color to be suggested by design team) and no drop shadow (shown below). We can offer the choice of dark vs light background as a variable if necessary.

![image](https://user-images.githubusercontent.com/13351591/42844769-030f3c60-89e2-11e8-80bb-a5efe95c34ca.png)

Slack Tooltip Example:
![image](https://user-images.githubusercontent.com/13351591/42845101-efc0b746-89e2-11e8-9e5e-2713185b835f.png)

Github Tooltip Example:
![image](https://user-images.githubusercontent.com/13351591/42845335-96c8b9ee-89e3-11e8-8a40-af029004feef.png)

**Comment by LHinson** [comment]
@trahman73 This issue will be closed out with the current tooltip PR therefore I'm separating this out as its own issue so we can continue to follow up on it. See #474

**Comment by jeperry** [comment]
+1 This seems to be the norm for other design systems like [Material](https://material.io/design/components/tooltips.html#placement) and [Lightning](https://www.lightningdesignsystem.com/components/tooltips/). Using an inverted color scheme also helps the tip stand out on the typically light background. I think using 16px is harmonious with the overall system since it is half the standard padding.

**Comment by LHinson** [comment]
This has been merged so I'm closing this issue.
