### ISSUE TITLE
Use of `vh` units in `.pf-c-page` `height` causes wonky scrolling issues in iOS

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-next#1174]
Note the weird rubber-banding effects causing the inability to get to the bottom of the content or to get the masthead to reappear at the top.  Fast scrolling causes the bug.  Stopping, allowing the browser to settle, and re-scrolling works around the bug.  http://recordit.co/luzQgzPjXq

Changing `100vh` to `100%` appears to resolve the issue.  http://recordit.co/UdyVl6Mks7

https://css-tricks.com/the-trick-to-viewport-units-on-mobile/#article-header-id-0 outlines the issue in detail.

cc: @spadgett, @janwright73

**Comment by mcoker** [comment]
FYI, this will likely require the ancestors of anything with `height: 100%` to also be `height: 100%`.

For example, if we have

```
<html>
  <body>
    <div class="pf-c-page">
```

Then both `html` and `body` will need `height: 100%` as well. This is the case for any component we want to be `height: 100%`.

Note that this will require some work in the workspace to get the page demos to work since gatsby helmet creates a bunch of `div`s between `<body>` and `.pf-c-page` in our workspace. @dgutride can likely help out with that.

**Comment by christiemolloy** [comment]
What I've seen with this issue so far:
1. Changing pf-c-page--Height - from 100vh to 100% changes the component to look like this: 
<img width="728" alt="screen shot 2019-01-22 at 12 13 56 pm" src="https://user-images.githubusercontent.com/20118816/51626727-332b7500-1f0e-11e9-88c9-2d8b6bb3dc26.png">

2. I'm having trouble applying height: 100% to every div from `<html>` to `.pf-c-page`. I can't target the divs with no id or class.

**Comment by mcoker** [comment]
I chatted with @dgutride about this and we agree it's OK if the workspace breaks but we fix the issue in core. He also agreed that we could address the workspace by hacking something into workspace.scss like `html body > div { height: 100%; > div { height: 100%; > div { height: 100%....` to target all of the elements that come before `.pf-c-page` in the page examples. We should try and get this fix into core by beta though.

**Comment by christiemolloy** [comment]
@mcoker ok sounds good will put a PR up for what I have been doing, shortly.
