### ISSUE TITLE
Message Dialogs - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1179]
Create design guidelines for use and creation of common message dialogs including error and confirmation dialogs of different types. Reference PF3 content here: https://www.patternfly.org/pattern-library/communication/message-dialog/

Related demo: #556

**Comment by katierik** [comment]
@nlcwong has a design for destructive dialogs that differs from the [PF3 guidance](https://www.patternfly.org/pattern-library/communication/message-dialog/#design) that I think might be a change.
Instead of a secondary button style for "do not delete", she used the primary button. This was to bring more attention to the "do not delete" as it gets a bit lost when its the secondary style.

![200D58B0-A79F-406D-8B58-94114FFFD08E](https://user-images.githubusercontent.com/23172038/55887545-b0649e80-5b7b-11e9-889b-984decd76633.png)

**Comment by jknilans** [comment]
@katierik are you suggesting that modals should include a use case for two primary buttons to be displayed at once?

**Comment by mcarrano** [comment]
A new PR was created and has been merged. @jknilans thanks for all of your efforts on this!
