### ISSUE TITLE
Review Alert component wording, structure, and aria labels

### ISSUE THREAD

**Issue by andybraren** [patternfly/patternfly-next#1226]
While working on the AlertGroup component in #1136 there were a few ancillary discussions about alerts that I'm not sure were addressed in @matthewcarleton's recent #1208.

1. We should agree on and standardize the noun we use in the Alert component. It sounds like we favor the word "alert" over "notification" (discussed [here](https://github.com/patternfly/patternfly-next/pull/1136#issuecomment-452880939) in #1136 and [here](https://github.com/patternfly/patternfly-next/issues/854#issuecomment-453094745) in #854 with @jgiardino and @stacymcauliffe). If that’s still the consensus, I’d suggest we replace any instance of "notification" in the alert component with "alert" instead, including in the aria attributes and example text. The AlertGroup component will match this.

2. The HTML order of an alert with a close button now goes Button > Title > Description all within `.pf-c-alert__body`. Previously the close button was included within `.pf-c-alert__action` which came after the Title/Description of `.pf-c-alert__body`. Is presenting the close button before text okay/preferred from a screen reader perspective @jgiardino?

3. The `aria-label` of close buttons should probably be “Dismiss” (discussed [here](https://github.com/patternfly/patternfly-next/pull/1136#issuecomment-451453573) in #1136) across all alerts.

**Comment by jgiardino** [comment]
Thanks for capturing these items, @andybraren!

My recommendation would be to remove the Dismiss button from the element with `role="alert"`. We can either move that attribute to a new div that wraps just the text, or move the button out of `<div class="pf-c-alert__body" role="alert">`.

When testing this attribute in the past, I had noticed that of the contents inside an element with `role="alert"`, only the text is announced, and not type of elements. I'd have to test again to know for sure if that's across all the screen readers we test again or not. But regardless of whether the element type gets announced, I think it would be really odd to have the beginning of the alert message start off with "Dismiss Success alert Files successfully uploaded Success alert Files successfully uploaded."

I do like that the button comes before the header in the Alert. If the screen reader user does happen to shift focus to the Alert, having a consistent pattern of "Close/Dismiss" Button > Header > Description/Contents for all of our components will ultimately be really helpful for screen reader users.

**Comment by matthewcarleton** [comment]
This all sounds good to me 👍 

@mcoker and I discussed "close" vs "dismiss" and settled on close. But I feel like we need to define if one makes more sense than the other depending on if it's a toast or an inline alert. @stacymcauliffe @jgiardino it would be great to hear your thoughts on that :)

With the way the alert is designed to be both inline and toast we may need to consider how unique this component is. If it makes sense we should present clear docs on how the a11y differs depending on its use.

@jgiardino I'm in favour of moving the dismiss button outside the `role="alert"` div. It will present some spacing issues, but I think it's more sensible to tackle that issue than introducing more markup that separates the inline and toast alerts even further.

**Comment by jgiardino** [comment]
I don't feel strongly about this, but I tend to prefer "Close" over "Dismiss" not because I think the term is better, but because it most likely works just as well, and allows us to minimize the set of terms we're using, and avoid having to document why you'd use one term here but another term there. I feel like I should keep going just to make a point that reading is really exhausting for some people and they just won't do it, so even if we do document things really well, there will likely be a mix of Close and Dismiss all over.

> With the way the alert is designed to be both inline and toast we may need to consider how unique this component is. If it makes sense we should present clear docs on how the a11y differs depending on its use.

Yes, definitely agree on the need for documentation. 

> I'm in favour of moving the dismiss button outside the role="alert" div. It will present some spacing issues, but I think it's more sensible to tackle that issue than introducing more markup that separates the inline and toast alerts even further.

👍  This makes sense to me.

**Comment by stacymcauliffe** [comment]
Agree with Jenn - standardize on one word for simplicity. Close works.

**Comment by andybraren** [comment]
Great, so 2 and 3 seem to be agreed upon. We'll use `aria-label="Close"` on every close button and we'll work on moving the dismiss button outside of the div with `role="alert"` to improve the screen reader readout.

Back to 1, if we similarly want to "standardize on one word for simplicity" it seems like we should decide whether to call these things "alerts" or "notifications" and make sure we refer to them as such in the documentation and examples of both the Alert and AlertGroup components. Right now the Alert component's examples refer to themselves as "notifications" (e.g. "Warning notification title"), but in [#854](https://github.com/patternfly/patternfly-next/issues/854#issuecomment-453094745) we discussed using "alert" to describe both inline and toast alerts (which is what AlertGroup does).

I lean toward "alert" given that's what the components themselves are named. "Toast alerts" would be what our documentation calls alerts positioned in the top-right corner. If toast alerts ever become unique enough to warrant becoming their own full-fledged component, that would seem like the appropriate time to start calling them "notifications".

**Comment by jgiardino** [comment]
I'm also good with "Alerts" and am making an assumption that we're moving forward with that term? (unless anyone chimes in soon in favor of "Notifications")

I had a chat with @matthewcarleton and @seanforyou23 about structure of alerts, and there are a few tweaks that we'd like to test, but also feel pretty good about putting in while we work on building a test page (#1253).

- `role="alert"` can be removed from individual alerts, and instead placed on the AlertGroup
  - This means that the Close button will be announced as part of the alert, and as a result should come after the alert text.
  - Depending on the test, we might also want to add `aria-atomic` but we will note that in a separate issue if that's the case.
- The Close button will use only `aria-label` instead of `aria-labelledby` so that the consumer can better control how to define those button labels, and avoid have button labels that repeat the entire heading.
  - This means that if the heading is announced as "Success alert: Batch upload completed successfully," then the consumer could define the button label as "Close success alert: batch upload"
