### ISSUE TITLE
Context Selector 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#133]
Introduce context selector

PF4 Visuals: [Design PDF](https://drive.google.com/open?id=1b405W_CGasRR-C7eZZl7KgigYODvtsMi)

This should be functionally equivalent to the context selector as specified here http://www.patternfly.org/pattern-library/navigation/context-selector/#design Note the option to have an inline search box.

**Comment by LHinson** [comment]
@kybaker will you please add the visuals for this to this issue.

**Comment by kybaker** [comment]
[Design PDF](https://drive.google.com/open?id=1eAmYtHi_Wgm92l6JnG-lKxi62SfaPOAn)

**Comment by matthewcarleton** [comment]
@mcarrano if you take a look at the new context selector you'll see there is no longer a scroll on the list unless it doesn't fit into the viewport. We may want to update this in the design if we want to use it to accurately influence the new design.

**Comment by kybaker** [comment]
@mcarrano Since we are breaking up with Bootstrap this serves as an opportunity for us to look at the functionality of the Context Selector. After speaking with @matthewcarleton I suggest we remove the search functionality that came with the default bootstrap widget. This functionality becomes complex at smaller responsive states.

**Comment by mcarrano** [comment]
@kybaker @matthewcarleton The search capability was actually important for some use cases. It this is being used as an object manager for example, there could be a larger number of entries in this menu (maybe 100 or more) and it's not really friendly to require the user to scroll through them all. So the idea is to be able to filter the list by typing into the search field.

**Comment by kybaker** [comment]
@mcarrano I added the search back into the mockup. I used the alternate field style you see in the login. When putting the field in a smaller box it reads better to use the underline instead of putting a box within a box. This was not as noticeable in PatternFly 3 since the fields were much smaller.

**Comment by mcarrano** [comment]
Per 5/17 design meeting -- should be updated to place search above the scroll area.

**Comment by LHinson** [comment]
This has been kicked back to visuals to ensure that everything is up to date before proceeding with dev. @kybaker to add final hi-fi images to description.

**Comment by kybaker** [comment]
Made updates to include the latest styling - https://drive.google.com/open?id=1b405W_CGasRR-C7eZZl7KgigYODvtsMi

**Comment by mcarrano** [comment]
Looks good to me @kybaker . I actually like this better in the context of the header than the rounded button we had before.

**Comment by mcoker** [comment]
The dropdown menu itself looks like it should be a div, and the first item in it can be an input gropu component for the search function, followed by a `ul` that displays the list of items in the dropdown. There is a similar structure in the "Select - Checkbox (Expanded)" example in the select component where we're using a `div` instead of a `ul` for the dropdown menu.

**Comment by christiemolloy** [comment]
@mcoker just to clarify this is a dropdown example not select?

**Comment by mcoker** [comment]
Oh sorry, no this is a new component modeled after a select.
