### ISSUE TITLE
SCSS import fails if extension is omitted and there is a .scss and .css file

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1370]
From @mindreeper2420. He's getting this error from `patternfly.scss` with the line `@import "./patternfly-base";` when both `patternfly-base.scss` and `patternfly-base.css` exist.

> Looks to be an issue with the `node-sass-chokidar` wrapper when importing items from the `node_modules` directory. It can’t determine which is the correct file to import, since it sees multiple with the `patternfly-base.` name. This is the message I get

```
"message": "It's not clear which file to import for '@import \"patternfly-base\"'.\nCandidates:\n  patternfly-base.scss\n  patternfly-base.css\nPlease delete or rename all but one of these files.\n",
```

Should we specify `.scss` extensions in our imports so this doesn't happen?

cc @dgutride

**Comment by alexkieling** [comment]
This issue is happening to me as well. I can manually fix it by changing the first line of `patternfly.scss` from `@import "./patternfly-base";` to `@import "./patternfly-base.scss";`. Unfortunately, that's not practical because `patternfly.scss` gets replaced when PatternFly is upgraded and it would not work in a CI server.
