### ISSUE TITLE
Tri-state checkbox

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-next#1411]
As a user I want to be able to select all items in table, deselect one row and see that select all checkbox is in third state (not selected and also not deselect) to indicate that some items are still selected.

**Comment by rachael-phillips** [comment]
Hi Karel, can you tell me how high priority this is? Right now, we have this as "future" on our roadmap.

**Comment by karelhala** [comment]
We found out that this would be good to have in 2 places (multiple filter dropdown - not well designed as of yet) and table (linked issue). But overall improved checkbox would be really good to have, custom browser checkbox seems a bit off with the rest of PF components. Just a suggestion (I know you guys can make better designs than I do) can we use these icons in future checkbox?
![screenshot from 2019-02-14 16-09-39](https://user-images.githubusercontent.com/3439771/52796045-59f34c00-3073-11e9-8be8-1097e3f05839.png)
![screenshot from 2019-02-14 16-09-47](https://user-images.githubusercontent.com/3439771/52796046-59f34c00-3073-11e9-9391-85d6d3bb43dc.png)
![screenshot from 2019-02-14 16-10-19](https://user-images.githubusercontent.com/3439771/52796048-5a8be280-3073-11e9-9299-38dbed775aa0.png)

**Comment by rachael-phillips** [comment]
Hi @karelhala thanks for the information. This is helpful. Do you have a timeline around when this is needed or is this blocking implementation?

**Comment by ryelo** [comment]
@rachael-phillips we're currently supporting checkboxes in just about every app, right now, we still support the "tri-state", but there is no visual design difference from the regular checkbox.

So it's not necessarily blocking anything in the sense of usability, but it is blocking because users might get confused if they're selecting things in tables.

**Comment by rachael-phillips** [comment]
Ok thank you for letting me know @ryelo - that helps!

**Comment by rachael-phillips** [comment]
@karelhala we think this could be a great contribution. Thanks for following up here!

@mcarrano could you weigh in here from the design perspective? Do you have any concerns design-wise?
Also, @jgiardino any concerns or thoughts about what we should keep in mind for a11y on tri-state checkbox?

**Comment by jgiardino** [comment]
I found this [css-tricks article](https://css-tricks.com/indeterminate-checkboxes/) that explains how to get this behavior with JS. Based on this, it should be possible to assign the `indeterminate` property to a checkbox via JS and have the native checkbox input visually display that state. 

I tested this using a [codepen](https://codepen.io/jenngiardino/pen/qzOOvz?editors=1111) of our Check component and running JS to apply the indeterminate property, and it does work with our current core implementation. 

@karelhala or @ryelo have tried this method already? Would this be sufficient for you, or is there something else you expect to be handled in the context of core? This doesn't seem to be something that needs to be handled in the context of html/css with our current solution. This is something they note in the css-tricks article:
> You can't make a checkbox indeterminate through HTML. There is no indeterminate attribute. It is a property of checkboxes though, which you can change via JavaScript.

However, there is this other issue — https://github.com/patternfly/patternfly-next/issues/865 — where the final solution might result in a custom styled checkbox. If that's the case, then we would definitely need to handle the visual styling of the indeterminate state with the `:indeterminate` pseudo selector.

And also, there is an aria attribute `aria-checked` that takes a value of `"mixed"` for indicating this indeterminate state. I only tested it in VO and nothing is announced (in that it announces the checkbox as "unchecked"). I'd still recommend that this aria attribute be used, because other screen readers may support it or eventually will support it. 

Maybe for now, the only thing to do in core is to include information in our documentation section of the Check component that explains how to get this state with JS? I'm also wondering if this property can be enabled as part of our react component, and if we should open an issue in our react repo?

**Comment by karelhala** [comment]
@jgiardino thanks for the investigation and further explanation. While I was checking for this issue I looked around and found `indeterminate` as well, it works as expected and it allows 3rd state as we need it to work. I went ahead and implemented JS solution as well [1].

Let's keep this issue opened so we can track the visual change of checkox, it would be really awesome to have svg icons instead of default look from browsers (that way we'd have same experience on any system).

[1] https://github.com/patternfly/patternfly-react/pull/2252#issuecomment-501788787

**Comment by jgiardino** [comment]
Thanks, @karelhala! You're way ahead of me on this! 😉 

After digging around a little more, I think the aria-checked property is only valid with custom checkbox components, but not the native `<input type="checkbox">`.

So I agree with you. Let's keep this issue open to capture the need for including this state of a checkbox if/when we implement custom styles. AND I'd also like to throw out a request that if we do implement custom styles for checkboxes, that at least for the tri-state version, we implement this as custom html implementation following the pattern that's documented by [wai-aria](https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-2/checkbox-2.html) so that we can semantically indicate the indeterminate property with aria-checked.

**Comment by mcarrano** [comment]
@karelhala @rachael-phillips I agree that this is something we will want from a deign perspective. There is a related issue open here for bulk selection that will apply this to bulk selection in a list or table: https://github.com/patternfly/patternfly-next/issues/1089. Yes, this is something that we might need to address in Core together with the custom checkbox issue.

**Comment by LHinson** [comment]
@karelhala we are working on issues to introduce the bulk select including: 
- https://github.com/patternfly/patternfly-next/issues/2161 (complete) 
- follow up in react https://github.com/patternfly/patternfly-react/issues/2758

We are opting to leverage the tri-state checkbox that was introduced in this PR here: https://github.com/patternfly/patternfly-react/pull/2252

I'm going to add an issue to ensure this is better documented that we have this. 

Just FYI

**Comment by LHinson** [comment]
We are proceeding with the tri-state checkbox seen in React. Can I close this one @mcoker?

**Comment by mcoker** [comment]
Yep!
