### ISSUE TITLE
Paginaion - wrong width

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly-next#1536]
It looks like pagination is using input type number, such type however does not support `size` attribute [1]. When adding large numbers the number is hidden behind input borders, because this input has width set. We shouldn't set width for this field because its size is calculated by browser from `max` attribute (to allow all characters).

[1] https://www.w3schools.com/tags/att_input_size.asp
> The size attribute works with the following input types: text, search, tel, url, email, and password.

**Comment by mcoker** [comment]
@karelhala the main purpose behind setting `type="number"` was to disallow non-numbers in that field. This was a requirement from design, so we based the width on the field size with 2 numbers in it. Assuming you're suggesting setting `size` instead of css `width`, wouldn't you still have the issue of large numbers being cut off because the input width is still limited in width, except now by a different attribute? 

One benefit to using `size` over css `width` would be that you could potentially change the `size` via a prop in react, instead of setting `--pf-c-pagination__nav-page-select--c-form-control--Width` in CSS for the input if you wanted to change the input width. I'm assuming that might be easier?

How would you like to see it work instead?

**Comment by mcoker** [comment]
cc @mcarrano

**Comment by karelhala** [comment]
Yeah, I understand the reasoning behind input type number. But as it's said in documentatin `size` prop has no effect on this type of input unfortunately. But browsers are smart enough to change the size of number input by themselves so if we set `width: auto` for this particular input it will shrink if maximum is small number and if maximum will be some huge number the input will be wider.

**Comment by mcoker** [comment]
Ah gotcha! Agreed, thanks for bringing this up.

**Comment by mcoker** [comment]
Looks like [Firefox needs a CSS width](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Controlling_input_size). I'll submit a PR to remove the `size` attribute.

**Comment by karelhala** [comment]
Yeah that is a big bummer. I guess we're gonna have to add custom styles to pagination in react so we can see page number bigger than 10
