### ISSUE TITLE
Options menu hidden label updates

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1694]
We use a hidden label in the options menu (and select) components for use when the toggle text is not static and changes based on the menu selection. If the toggle text does not change upon selecting something in the menu, the hidden label is not needed.

We should remove the hidden label from all of the examples except for the "Options Menu - Plain with text" example, and update the menu item text in that example to "5 per page, 10 per page, 20 per page" with "10 per page" selected. 

And then ensure anywhere else we're including the options menu component in a component or demo, that we're using the hidden label appropriately.

And it probably makes sense for the label to have a BEM class, and we use `.pf-screen-reader` to hide it visually, and to document the use of this label in the component documentation. Assuming we do this, we should also update the Select component to match.

**Comment by jgiardino** [comment]
Thanks for capturing this issue! Just a couple of comments to add...

**1**
> And it probably makes sense for the label to have a BEM class, and we use .pf-screen-reader to hide it visually, and to document the use of this label in the component documentation.

I'm not sure this is right. This element is hidden using the `hidden` attribute, and doesn't need css to hide it. This label isn't perceivable by screen readers where it is in the DOM (because it's hidden), but the `aria-labelledby` on the toggle will associate the label with the toggle and therefore announce the text along with the text in the toggle. 

If this element doesn't need styles, is there any benefit in providing a BEM class for it?

**2**
When updating the pagination component as part of this issue, and remove the hidden label, we should incorporate that string into the button so that it would end up like this:
```
<button 
  class="pf-c-options-menu__toggle-button" 
  id="pagination-options-menu-top-example-toggle" 
  aria-haspopup="listbox" 
  aria-expanded="false" 
  aria-label="Select items per page">
```

**Comment by mcoker** [comment]
> is there any benefit in providing a BEM class for it?

I guess that section was more of a question :) You're right, I don't see any advantage of `.pf-screen-reader` over `hidden`. Giving it a BEM class because it's an element that serves a particular purpose and should be documented as to what it does. Doesn't need a class for that though. We can just refer to it as `.pf-c-options-menu > span` in the documentation instead.

**Comment by mcoker** [comment]
Completed in https://github.com/patternfly/patternfly-next/pull/1759/files
