### ISSUE TITLE
Reduce the width of the left side of the wizard  

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#1742]
The area, where the steps are located, on the wizard should be reduced to allow for more space in the content area. 

No additional visual assets are required for this issue, however CSS and Visuals should work together to ensure the best result. 

This is somewhat related to #1740

**Comment by mcoker** [comment]
I opened these issues after talking to @kybaker this morning:

https://github.com/patternfly/patternfly-next/issues/1736 (add a modifier for the narrow nav)
https://github.com/patternfly/patternfly-next/issues/1737 (make this the default in our next breaking change release)

But if we can change the wizard layout now since people haven't adopted it as a component, I can close those issues and track the work in this issue.

**Comment by LHinson** [comment]
@mcoker I'm cool with proceeding with your issues. I'll close this one and get back to you re: the usage so we know which way to proceed. Thanks!
