### ISSUE TITLE
Alert styling is off when used inside AboutModal

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-next#1754]
I'm seeing a padding/styling issue when I use Alert inside an AboutModal:
<img width="1214" alt="Screen Shot 2019-04-23 at 4 30 30 PM" src="https://user-images.githubusercontent.com/7014965/56613676-21c53800-65e5-11e9-8a5a-456e9e0e38e6.png">

I think it's caused by .pf-c-content targeting the h4s. We need to use Alert like this in OpenShift -- any chance you guys can take a look?

**Comment by mcoker** [comment]
@rebeccaalpert I wouldn't expect you to nest an alert inside of the content component. In that case, I would expect to use a content component followed by the alert, followed by another content component.

**Comment by rebeccaalpert** [comment]
I think PF4 React places all of the children in a .pf-c-content div automatically. I don't see a way to override that as-is. Should I be opening an issue with patternfly-react instead?

**Comment by mcoker** [comment]
I think so. @mcarrano is nesting the alert in the about modal like in the screenshot supported? If so do you agree that a user should be able to put any component they want in the body of the about modal, and if they want normal heading/paragraph/list/etc styling, they would explicitly use the content component?

**Comment by mcoker** [comment]
Something else worth noting is that if you nest a content component and an alert (or any type of component) in the content area of the about modal, there will be no spacing between those components by default. You would need to use a layout, like a [flex column layout](https://pf4.patternfly.org/layouts/Flex/examples/) or [margin/padding utility classes](https://pf4.patternfly.org/utilities/Spacing/examples/) to create the spacing. 

A way we could support default spacing there would be to add a "body" element to the about modal box content area that could hold one or more components, and we create vertical space between those body elements. We do something similar for the card with [multiple card bodies](https://pf4.patternfly.org/components/Card/examples/).

**Comment by mcarrano** [comment]
@mcoker @rebeccaalpert This is not something we support from a design standpoint. What is the use case here? The About modal was not intended to communicate dynamic content like this. If this is a requirement, then we should take a step back and consider how to communicate alerts and messages from within the About dialog

**Comment by rebeccaalpert** [comment]
@mcarrano UX made [these designs](http://openshift.github.io/openshift-origin-design/web-console/4.0-designs/cluster-settings/cluster-settings) related to cluster updates. @bmignano, would you be able to speak to the use case?

**Comment by beanh66** [comment]
@mcoker @mcarrano We designed this awhile back with @maryshak1996 and @kybaker. Kyle, can you chime in here? It was my understanding we could use inline notifications inline on a page or modal. Is that not the case? 

It isn't a huge deal, but we felt it was good to show the available update next to places where the current version is listed since it's an important action to take that results in a version change.

**Comment by kybaker** [comment]
@mcarrano I think it is totally valid to put an inline notification or other form elements here. I supect this just comes down the the way we are using the CSS. Could we allow the about to function like any other modal?

**Comment by mcarrano** [comment]
We could. But it was not something we considered during the initial design. I'll defer to @mcoker on what would be required to make this work. Is a change to the core CSS required?

**Comment by mcoker** [comment]
@mcarrano the most simple fix is a react change so that you can put any type of content in the body of the modal. Currently the react component nests everything you specify in the body in a Content component. That wouldn't require an update in core, other than updating our documentation to remove the content component from the list of components used to construct the about modal.

I think they could do that on the react side by adding a prop that makes the component not nest the body content in a Content component. Though I think long-term, we might want that to be the default (like the Modal), so that if you want to use the Content component, you just pass that in with your body content.

@rebeccaalpert do you want to open an issue on the react side?

**Comment by rebeccaalpert** [comment]
Yeah, no problem. Should I close this one or leave it open for the doc change?

**Comment by mcoker** [comment]
@rebeccaalpert thanks! Let's leave this one open.
