### ISSUE TITLE
Introduce masthead utility menus to Page Layout demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#1833]
Define standard masthead utility menus - organization and content and incorporate into the standard page layout demo. Need to consider what menus are required and how content is organized. Consider requirements for user management, help, support, language selection, and other settings.

Results should be incorporated into the existing page layout demo.

Related issues: #1832 , https://github.com/patternfly/patternfly-org/issues/714

**Comment by mcarrano** [comment]
@dongniwang per our discussion, I have created this issue and assigned in to you for discovery work. I am working with @maryshak1996 on a separate issue to better define the behavior of utility items in general as a first priority. Once we have standard menus defined, the goal would be to implement as a demo and publish design guidelines to the website. Let me know if you have questions.

**Comment by jeperry** [comment]
FYI, if you log in with your Red Hat Account you can see the early attempt at cloud.redhat.com. Screen shots here for convenience.  

![image](https://user-images.githubusercontent.com/2206023/57889588-315e2800-7803-11e9-996a-a3c00218aeca.png)
 
![image](https://user-images.githubusercontent.com/2206023/57889600-3de28080-7803-11e9-827a-1c74990f162c.png)

**Comment by dongniwang** [comment]
@mcarrano thank you! 

@jeperry thank you for the screenshots! Two questions: 
1. The "username" and "account number" in the first screenshot are greyed out, is there a reason for it? For the user avatar, is it clickable? How would users update their avatars? 
2. The second screenshot (help dropdown menu) - is there a reason behind opening the links in the existing browser tab instead of a new tab?

**Comment by jeperry** [comment]
1. username and account number are included as information only. These are necessary for account differentiation, but they are static info and cannot be clicked, so that is why the text treatment is different than actionable menu items below the divider. The clickable area to invoke this menu is the user name and the arrow,  the avatar is not included in this. Avatar image is updated via Customer Portal profile (on another domain) which is reached via the link "My Profile." 
2. The first three links are on different domains and should probably open in another tab, but have not been implemented this way. Is there a design pattern to indicate links in these menus that open new tabs vs those that do not? 'About' simply opens the about modal.

**Comment by jeperry** [comment]
fyi @KendraMar

**Comment by KendraMar** [comment]
@dongniwang Hi, the Cloud Services team is asking about the avatar as well. Here's what one of the team reported in Jira:

"currently the user avatar icon sits without a way to interact with it directly beside the username/action drop-down

other websites/apps like google, Jira, github and manymorehave the icon integrated with that user actions drop-down, or even use only the icon as a way to open the drop-down/context

i believe that from a ux familiarity standpoint the icon should be either integrated into the drop-down or at least trigger it as well"

**Comment by dongniwang** [comment]
Thanks for the info @jeperry and @KendraMar !

**Comment by mcarrano** [comment]
Documentation on potential menu items can be found here: https://docs.google.com/document/d/1fuII5EhFAQMtYpSBOLPgWPLuQ0cQUgHVUbmSjrtMUJE/edit?usp=sharing

**Comment by maryshak1996** [comment]
My working doc: https://docs.google.com/document/d/1iN-FV-JsS1kial7wza7GG4Vu4jA0KfaXaxz5a0lrYcU/edit?usp=sharing

**Comment by mcarrano** [comment]
In the interest of reducing duplication, I am closing this out in favor of the related documentation issue referenced above. This seems like primarily a doc problem.
