### ISSUE TITLE
Page Hamburger Menu should turn from hamburger to close button

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#1854]
@maryshak1996 want to provide some more info here :)

**Comment by maryshak1996** [comment]
I've been working on the notification drawer and was poking around at the react implementation for the vertical nav on mobile (I think that they could have the same responsive behavior, as they are both vertical slide in panels), and there's a couple of things I'm unclear on:

1. Is there a reason why the vertical nav doesn't span full-width on mobile? There's about 13-140 pixels of space where you can see through into the page content
2. Should the hamburger not turn into the close icon once it reaches this point, so that the user more clearly knows how to return to their page content? 
_React site vs Sketch file_
<img width="629" alt="Screen Shot 2019-05-23 at 3 53 42 PM" src="https://user-images.githubusercontent.com/19824574/58282551-13994180-7d74-11e9-9835-25e53fd6119e.png">

**Comment by rachael-phillips** [comment]
@mceledonia , @kybaker did you happen to see @maryshak1996 's questions above?

**Comment by mcarrano** [comment]
Per discussion with @maryshak1996 , will close.
