### ISSUE TITLE
Missing patternfly-charts.css

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-next#1866]
I see patternfly-charts.scss included in the latest package v2.8.2, but patternfly-charts.css is empty. 

I also don't see the charts included in either patternfly.scss, patternfly-base.scss, etc. 

In order for the react chart components to consume these variables, they must be available via react-tokens, which pulls vars from patternfly.css.

**Comment by mcoker** [comment]
We added the file as `patternfly-charts.scss` because `patternfly-*.scss` is compiled to CSS, and we wanted to offer both formats. But we were going to wait until we have the SCSS vars in place before adding the CSS vars to that file, which will eventually populate `patternfly-charts.css` with CSS.

> In order for the react chart components to consume these variables, they must be available via react-tokens, which pulls vars from patternfly.css.

What do you think about this @dgutride? It seems like this implies the charting vars need to be included in the core compiled CSS in order to be consumed by react. Should we ship the chart CSS in patternfly.css? I don't think it's going to end up being a lot of CSS (so far at least), so size isn't really a concern. Or should we approach how these vars are imported in react differently to allow them to be a separate stylesheet in core so that we don't include them by default and users can include the stylesheet if they're using charts?

**Comment by dlabrecq** [comment]
It may be possible to populate react-tokens from multiple CSS files. However, we need the CSS in order to begin converting the charts to use the color pallets. Can we at least get the colors added now?

**Comment by dgutride** [comment]
@dlabrecq @mcoker - I think we should keep them separate and update react-tokens to look at the separate stylesheet. Is there enough in the current patternfly package to do that or do we need to wait for the colors to be added?

**Comment by mcoker** [comment]
> However, we need the CSS in order to begin converting the charts to use the color pallets. Can we at least get the colors added now?

Gotcha, yes we'll add those today.

**Comment by dlabrecq** [comment]
@mcoker @christiemolloy Are the CSS colors available?

**Comment by dlabrecq** [comment]
Also, do the vars need to be formatted more like this?

```
:root {
  $pf-chart-color-blue-100: #8bc1f7;
}
```

Just doing some testing with react-tokens and it seems a block is required around the CSS vars. For example:

```
:root {
  --pf-chart-color-blue-100: #8bc1f7;
}
```

**Comment by dlabrecq** [comment]
@rachael-phillips Yes, I am aware that #1846 has been merged. However, the generated CSS file is empty, which is why this issue exists.

**Comment by christiemolloy** [comment]
@dlabrecq the PR is here: https://github.com/patternfly/patternfly-next/pull/1868 I'm just confirming with Dana and Rachael that we can merge it

**Comment by dlabrecq** [comment]
I see you added `:root` as well. Thank you!

**Comment by christiemolloy** [comment]
@dlabrecq , @dgutride said we should wait until we release in order to merge it, hopefully that will be today.
