### ISSUE TITLE
Consider Primary modifier for dropdown

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#1872]
Currently in OpenShift there is a dropdown that has a primary style applied. As we move over to PF4 dropdowns we'll need to update this and currently we don't have this type of dropdown in PF4.
<img width="367" alt="Screen Shot 2019-05-30 at 12 54 34 PM" src="https://user-images.githubusercontent.com/287880/58645627-1b0f9c00-82da-11e9-9dbb-a13a26c66b53.png">

Here's what this could possibly look like:
<img width="452" alt="Screen Shot 2019-05-30 at 12 53 56 PM" src="https://user-images.githubusercontent.com/287880/58645576-06cb9f00-82da-11e9-8564-13d014fb497c.png">

This is rough and stills need some polish (states, a11y) but it's a start.

fyi: @beanh66 @priley86 @lizsurette

**Comment by priley86** [comment]
any updates here? I think we are ready to start looking into this downstream soon. Associated OpenShift issue:
https://github.com/openshift/console/pull/1629

Direction on downstream customization/variable override would also be appreciated!

cc: @sg00dwin

**Comment by beanh66** [comment]
FYI @LHinson

**Comment by spadgett** [comment]
Hi, is this under consideration? We tried to use the primary button style on the dropdown in https://github.com/openshift/console/pull/1905, but it wasn't quite right. For now, we're using the default dropdown styles.

**Comment by ncameronbritt** [comment]
UHC needs something like this too.

**Comment by mcoker** [comment]
Should the hover/expanded state be darker to match the button?

<img width="586" alt="Screen Shot 2019-08-29 at 3 02 51 PM" src="https://user-images.githubusercontent.com/35148959/63972371-38393f80-ca6e-11e9-9945-1280033ee966.png">

And do we need to consider the use case where this will be used with the plain modifier and/or the split button?

<img width="286" alt="Screen Shot 2019-08-29 at 3 06 32 PM" src="https://user-images.githubusercontent.com/35148959/63972549-9a924000-ca6e-11e9-90ab-50a8ad8d2c3d.png">

<img width="363" alt="Screen Shot 2019-08-29 at 3 05 36 PM" src="https://user-images.githubusercontent.com/35148959/63972487-7df60800-ca6e-11e9-93db-623d2d187386.png">

**Comment by mcoker** [comment]
@matthewcarleton @kybaker ^

**Comment by mceledonia** [comment]
@mcoker I think this makes sense, similar to how our standard dropdown has an active state.

I'm not sure about the kebab, because kebabs (correct me if I'm wrong here) inherently contain secondary actions so a primary modifier seems to be almost an oxymoron. I can see a case for the split button perhaps though. I might actually defer to @mcarrano here to see if he has any ideas on the need for those.

**Comment by matthewcarleton** [comment]
+1 I agree with the active state, looks great!
We haven't seen a need for this for the split so I'd be reluctant to introduce it if it's just providing opportunity for inconsistency. Just my thoughts though.

**Comment by mcarrano** [comment]
Agree that the Primary Dropdown looks great and we should move ahead with that. I don't see a use case for a primary kabob or split button so I'd rather not introduce those at this time.

**Comment by ncameronbritt** [comment]
@mcoker @mceledonia Thoughts on a version of this that would be styled similar to a secondary button?

**Comment by mceledonia** [comment]
I don't see a problem with it, it makes sense as there's a need for primary and secondary buttons there'd be a need for a secondary button dropdown. For the above though, we would want the styling to match our buttons, so I'd say making sure the internal padding is the same as buttons as well as the corner rounding values. I know that's just a mockup but wanted to be sure!

**Comment by matthewcarleton** [comment]
@mceledonia if that's the case then we'd want to revisit the initial update where it's just a primary dropdown rather than a button with a dropdown.
I'm ok with either, I don't see much difference in either case. 🤷‍♂

**Comment by mceledonia** [comment]
I think it depends on how we treat it in the overall page hierarchy. Is it grouped with buttons in that there can only be one primary per page, or could we have both a primary button and a primary dropdown button in the same page? Probably a good question for @mcarrano, though my take was thinking of this as a button (primary or secondary) with a dropdown capability, rather than a sort of primary/secondary styled dropdown. Similar to if we were to have a primary/secondary button with some other icon. 

I definitely am open to hearing more thoughts on it though, it might make more sense as it is and I'm just already in thanksgiving vacation mode :slightly_smiling_face:

**Comment by matthewcarleton** [comment]
+1 
It came from a requirement on the OS side to see a primary dropdown from PatternFly but that doesn't mean it has to stay that way. 
An interesting thought too could be how this extends the button in general to accept an icon. We've discussed the idea of having a spinner in the button which could benefit from this update. 
I can open a new issue to cover this and reference this if that's useful. WDYT @mcarrano ?

**Comment by ncameronbritt** [comment]
In the particular case I'm working on, this button dropdown would be a peer to several other secondary actions on the page. This component may not be the only solution; I'm just exploring options.

**Comment by mcarrano** [comment]
We might be splitting hairs here, but the original ask was for a dropdown with primary styling which was what has been added in the library. Behaviorally I don't see this as a button since the action of clicking the body is to just toggle the menu. We recently introduced something called a Split Button that might be a better choice here. You can see that as a new Dropdown variant. @ncameronbritt can you take a look to see if that would address your use case?

**Comment by mceledonia** [comment]
@mcarrano I definitely see what you're saying, and I could really go either way but I still feel a little weird about it so I will try to explain with a quick visual using Cameron's example above with an additional secondary action. 

If "Create Virtual Machine" was the primary action on the page, without a dropdown capability, it would be a button like this:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/30935938/69736042-c077c100-10ff-11ea-88e5-87daf95d9a70.png">

So I guess where I'm feeling weird about it is that adding the dropdown capability to that primary action would switch it's styling from being rooted in a button to being derived from the dropdown (mainly manifesting in the rounded corners) 

From a visual standpoint I'd expect it to lead to this

<img width="438" alt="image" src="https://user-images.githubusercontent.com/30935938/69736061-ccfc1980-10ff-11ea-97d4-378cedd25634.png">

Rather than transforming to the dropdown styling like this:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/30935938/69736091-d7b6ae80-10ff-11ea-8a72-d8b4e253f3ab.png">

That being said I can't quite articulate what it is that's throwing me off. I think it's that at it's root it is a primary action, and therefore in it's singular form it would be a button, but in it's plural form I'd expect it would be a dropdown derived from the singular button rather than the other way around. The fact I can't really pinpoint it tells me I am really ok with either approach, but I figured it would be worth trying to articulate my thoughts as clearly as possible here 🙂 .

**Comment by mcarrano** [comment]
Thanks for this @mceledonia . Now I can see what you are talking about from a visual standpoint. This prompts a couple of questions for me. First, why are the stylings of the button and dropdown different? Would it make sense for them to have the same corner treatments?

Second is a question for @matthewcarleton and @ncameronbritt . Now that we have the thing called Split Button that combined a button and a dropdown, would that be more appropriate here than grouping buttons and a dropdown? Would help to understand better what's driving the need to do this.

**Comment by ncameronbritt** [comment]
This is my situation. There is a primary action at the top of the page. There are three sections in the main body of the page which each have an associated action. The sections are unrelated to each other, but related thematically to the tab they appear on. The first section has that action dropdown b/c you get a different form depending on which identity provider you choose to add. Again, this is not the only way to approach this particular scenario, but it's one that makes some sense to me. 

![Access control tab with IDP Copy](https://user-images.githubusercontent.com/8974593/69739274-70036200-1105-11ea-8047-3716bb814f67.png)

**Comment by matthewcarleton** [comment]
@mcarrano I am seeing this the same as you. It makes sense to just align our dropdowns and our buttons visually. Looking at other design systems this seems to be the common approach (Bootstrap, Polaris, Carbon). I'd vote for that, which would make everyone happy I think :)

@ncameronbritt If we did go that way it would provide you with a dropdown style that matches the button style you are using in your other sections. Not that this is a review of your design, but would it be possible to add the selection action inside the modal that pops up when you click "Add identity provider"?

**Comment by ncameronbritt** [comment]
@matthewcarleton totally possible, that's why I said this wasn't the only possible solution. In fact, right now you make the selection in the modal, but this is inconsistent with what OCP does. :-)

**Comment by mceledonia** [comment]
@matthewcarleton I'm definitely down for that, it would also help to clear up the use case for input group buttons/dropdowns, as that styling would only be used when they're tied to an input field. Right now for input groups there's the input styling which gets applied to buttons, but it also is the same styling as dropdowns.

I think the reason they were the same is because we designed them together, with input groups in mind from the start. Here's another visual to explain what I mean.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/30935938/69748843-2885d180-1117-11ea-8219-f6f2be602ea6.png">

**Comment by cntlsn** [comment]
A conversation about one of the topics discussed in this issue (Should the Primary toggle be styled more like a button or a default dropdown toggle?) also started last week at https://github.com/patternfly/patternfly-design-kit/issues/159

I think this issue was closed automatically due to a merged PR, but it feels like some questions are still relevant and didn't get a final answer.

Should this be reopened, or a new -more specific- issue about the styling issue be filed?
Or is this conversation already happening elsewhere?

**Comment by mcarrano** [comment]
My suggestion is to open a new issue @cntlsn . You can reference this issue for some history.
