### ISSUE TITLE
Tabs Component Link

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-next#1966]
https://www.patternfly.org/v4/documentation/core/components/tabcontent#documentation

Clicking "Tabs Component" link causes 404 error.

**Comment by mcoker** [comment]
@jschuler we have links in the overview of this component (and the [tabs component](https://www.patternfly.org/v4/documentation/core/components/tabs#documentation)) that link to the component in the core workspace, so they're 404'ing on the website. We probably have links like this in other spots, too.

Have you run into this before? Curious if we should we update those in core so they're absolute links instead of relative, and they link to the core workspace? Or do we want to keep users on the website and not link off to the core workspace? Maybe we should just unlink the text?

**Comment by janwright73** [comment]
@redallen - is this possibly related to your HTML refactoring to use markdown for documentation?

**Comment by redallen** [comment]
Nope! This is just a broken link. It can be fixed along with a ton of other changes in my PR, though.
