### ISSUE TITLE
React modal example has incorrect button styles

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-next#1969]
The modal dialog in the React examples has buttons on the *right*. As per the design guidelines, these buttons should be on the *left*. 

![react-modal](https://user-images.githubusercontent.com/23172038/59872158-2862f800-9367-11e9-8b53-8f9395ff1b63.jpg)

**Comment by mcoker** [comment]
We have https://github.com/patternfly/patternfly-next/issues/1599 with the original discussion around changing this. I don't think we should make that change until a breaking change period since changing the alignment would just shift the buttons to the left, and they would be out of order with the primary action to the right of the secondary.

@rachael-phillips @mcarrano can we add the breaking change label to #1599 and do it in the upcoming breaking change release?

**Comment by mcarrano** [comment]
There is already an open issue for this here: https://github.com/patternfly/patternfly-next/issues/1599 Suggest that we close this as a duplicate.

**Comment by mcarrano** [comment]
Yes, that was the plan @mcoker . I've added the breaking change label.

**Comment by rachael-phillips** [comment]
I am closing this issue as it is a duplicate
