### ISSUE TITLE
Bug: PatternFly CSS has side-effects on unrelated elements

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-next#2008]
PatternFly has CSS that changes pure DOM elements (such as `<a>`), this affects elements outside of PatternFly and is considered an unintended side-effect. PatternFly should not be able to modify elements I do not tell it to

If I wish to add PatternFly styling to something I should be able to do so through a class. Because otherwise PatternFly breaks my website and I have to do fire-fighting to restore it.

Only culprit I've found: https://github.com/patternfly/patternfly-next/blob/c6e0e46af9c8e5534e8840e57bfd823d61693729/src/patternfly/_globals.scss

**Comment by mcoker** [comment]
Hey Eric, in the future we do plan on making the global resets a requirement of PF4, since many of our components rely on global styles that we don't want to set in each individual component. That said, currently the stylesheet you linked can be excluded, although some PF4 components may still be missing styles found in the globals stylesheet.

Can you tell me more about how you're importing PF4 into your app? If you're using SCSS, you can see on https://github.com/patternfly/patternfly-next/blob/c6e0e46af9c8e5534e8840e57bfd823d61693729/src/patternfly/_globals.scss#L4 that this stylesheet can be excluded by setting `$pf-global--enable-reset: false;` in your SCSS before importing PF4. If you're importing all of `patternfly.[scss/css]`, you can use [patternfly-no-reset.scss](https://github.com/patternfly/patternfly-next/blob/c6e0e46af9c8e5534e8840e57bfd823d61693729/src/patternfly/patternfly-no-reset.scss), which is also compiled to `patternfly-no-reset.css` in our dist package.

**Comment by SpyTec** [comment]
I see, good to see that globals can be excluded in a few ways.

Should the globals not make more sense if it was classes? That way you only need to add the class names to the various elements. Then we would not loose styling from globals if we wish to import a PF4 project.

**Comment by mcoker** [comment]
Do you mean something like...

```
.pf-include-global body {
  font-family: // global font family
  font-size: // global font size
  ...
}

.pf-include-global a {
 color: // global link color
}

...
```

**Comment by SpyTec** [comment]
I would say 

```css
body.pf-include-global {
  font-family: // global font family
  font-size: // global font size
  ...
}

a.pf-include-global {
 color: // global link color
}

...
```

As it's then applied to the right element

**Comment by mcoker** [comment]
I see, thanks for the example. I think a change like this would create a separate variation of PF4 that we will need to support and test, since adding a class to the base elements increases the specificity of those selectors to 11, which is higher than a single class (10) that we use to style most of our components/layouts. Since we're moving toward making the global reset styles a requirement in PF4, I don't think this is something we want to add at the moment. However you're welcome to opt out of the global styles and duplicate the stylesheet with a custom class added to the element selectors and use this method if you'd like.

**Comment by SpyTec** [comment]
Alright, I will do the latter of using no-reset and implementing the globals myself in a custom class. Thanks for taking the time
