### ISSUE TITLE
Support column headers that wrap

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#2048]
Update: this issue should show an example of the table headers wrapping.

cc: @mcoker  @mcarrano

**Comment by mcoker** [comment]
@christiemolloy it is in the table component's documentation:

> Table header cells

> By default, all table header cells are set to white-space: nowrap. If a <th>'s content needs to wrap, apply .pf-m-wrap.

**Comment by christiemolloy** [comment]
Ah i see it now, I guess my question is should we show an example of them wrapping, so its more clear that we support it @mcoker

**Comment by mcoker** [comment]
Hmmm, I'm not sure if that needs it's own example, but maybe we could add an example (or a couple/few) in the existing examples of a `<th>` that has a lot of text and wraps?

**Comment by christiemolloy** [comment]
Yeah I think that would be helpful

**Comment by KendraMar** [comment]
@mcoker So we're saying that whether to truncate and/or wrap is up to the component consumer? We (UX) don't offer guidance on the max width on a column header title?

**Comment by KendraMar** [comment]
@mcoker I missed the wrap explanation on the Design and Overview tabs...is it only on the code tab?

Also, when I go to the code tab/react example, I'm not able to resize the columns to see how the table headers behave...am I supposed to be able to?

**Comment by mcoker** [comment]
> So we're saying that whether or not to truncate and/or wrap is up to the component consumer?

@KendraMar according to the documentation, I think so, but I agree that this is unclear. Also worth noting that @ncameronbritt opened a similar issue - https://github.com/patternfly/patternfly-next/issues/1994 I'll defer to @mcarrano as to whether we have a recommendation we can add to the table design or component documentation, or if it's up to the consumer to use as they see fit.


Re: the wrap explanation, I am looking on the PatternFly 4 site at https://www.patternfly.org/v4/

The table header wrap documentation is under the "Documentation" tab, in the Core/HTML framework's Table component - https://www.patternfly.org/v4/documentation/core/components/table#documentation

We also have a "Lists and tables" design documentation page under the "Design guidelines" tab here where I might also expect to find documentation on when/how to wrap/truncate table header content - https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/lists-and-tables#data-tables

**Comment by KendraMar** [comment]
Thanks, @mcoker !

**Comment by mcarrano** [comment]
@KendraMar do you think this is something we should have a specific design guideline about? What do you propose? I'd be fine to add something to the design documentation, but not sure what I'd say. In general I feel that column headings should be short so I would not encourage wrapping except as a special case.

**Comment by KendraMar** [comment]
@mcarrano 

is it good enough to just say that -- please avoid wrapping (and do we support 2 lines only)? Try to keep your header title to 20 chars or fewer?  Also, does this mean we'd rather they truncate a long header name instead of wrap? I guess, in general, I'd rather the component support/present the behavior we'd like to see and force the product dev to override it to do things we don't really want (ie, wrap).

So, with my limited POV of Cloud Services, I'd ask my team to set guidelines  for Cloud Services like this (I think):

Column headers should be no more than 20 characters; truncate after that. 
Only wrap a header (2 lines max) if truncating the column header makes it too difficult to scan and distinguish it from other headers.

If this is too limiting for other products' use cases, I can just share this with my team for their comment. 

@christiemolloy Thanks for acting on that so fast!
