### ISSUE TITLE
Provide In-page wizard demo

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#2073]
Currently the wizard only ships in a modal. In OpenShift we have the requirement for an in page wizard.
It would be great if the wizard was broken out of the modal and was capable of being dropped into the content area of the page.
Here is a wireframe of what this could look like:
![create-vm-inline-wizard](https://user-images.githubusercontent.com/287880/61402742-24fd5680-a8aa-11e9-903d-acb6e73809b5.png)
With an in-page wizard it could be useful to consider removing the fixed width from the steps section to provide more space for the content area.
<img width="897" alt="Screen Shot 2019-07-17 at 3 49 53 PM" src="https://user-images.githubusercontent.com/287880/61402928-8de4ce80-a8aa-11e9-9b5c-62af9c6c8bdc.png">
this could be related to the work done for #2046 , #1242, and #1970

**Comment by mcarrano** [comment]
Thanks for opening this issue @matthewcarleton . I'd like to elaborate a bit more based on our conversation. I believe that this request can be accomplished by refactoring the current modal wizard into it's component parts. These components can be used for creating either wizards or progressive forms contained in a modal or full page view. This would give us the flexibility to support a number of desired workflows. This may entail the following work items:

* Break the wizard into it's component parts: wizard header, stepper, actions bar. These could be contained in a wizard layout that could be dropped into a modal or the content area of a page.
* Refactor the current wizard to be built using these components.
* Use these components for building out related components and demos including the [Progressive Form](https://github.com/patternfly/patternfly-next/issues/1242) and In-page Wizard (demo?)

@mcoker @kybaker @LHinson would be interested in your thoughts on this approach.

**Comment by mcarrano** [comment]
Once we perform work to remove the wizard from a modal, we should create a demo to show how it can be used within a page.

**Comment by mcarrano** [comment]
Moving to the CSS backlog. Design recommendation is to not use a card behind the wizard as shown in the mocks. @mcoker once you have an example of this, please tag @kybaker and myself so we can review and adjust spacing, if necessary.

**Comment by matthewcarleton** [comment]
@mcarrano that's great! Glad to see the progress here.Not sure if it was mentioned but we might want to remove the box shadow on the steps as well, might look on a grey background.

**Comment by mcarrano** [comment]
@matthewcarleton not sure how much customization we can support on the visuals, but @mcoker @kybaker can you comment?

**Comment by mcoker** [comment]
Changing the box-shadow to a border to reflect the design in the screenshot posted above is no problem for this variation.

**Comment by matthewcarleton** [comment]
@mcarrano I am assuming when you say 
> Design recommendation is to not use a card behind the wizard as shown in the mocks
you're saying the wizard would just be on the grey background from the page component. Have we seen a design for this? I would be concerned that the box-shadow that is currently in the wizard would look odd. Maybe this has already been tested and it's not an issue. If so, ignore me :)

**Comment by mcarrano** [comment]
@kybaker can you comment?

**Comment by kybaker** [comment]
@matthewcarleton I do not see a need for a gray border here we can just make this extend the full width of the screen. Not every layout is required to be in a card.

**Comment by matthewcarleton** [comment]
ok just to clarify (and maybe I'm the only one that needs it)
This is more what we are talking about (very rough)
<img width="791" alt="Screen Shot 2019-08-08 at 9 34 52 AM" src="https://user-images.githubusercontent.com/287880/62703912-9d929700-b9c0-11e9-84c3-fdf7c0ecf47a.png">

**Comment by kybaker** [comment]
@matthewcarleton Yes that looks great.

**Comment by mcoker** [comment]
@matthewcarleton @kybaker @mcarrano 

Here's some initial work. Question - is the header optional in the in page variation, or should it never be included?

Regular desktop view:

<img width="1792" alt="Screen Shot 2019-08-22 at 5 03 44 PM" src="https://user-images.githubusercontent.com/35148959/63553027-e852f980-c4fe-11e9-9383-2a7bd5059315.png">

Just before the first breakpoint with page component's vertical nav expanded

<img width="1119" alt="Screen Shot 2019-08-22 at 5 03 51 PM" src="https://user-images.githubusercontent.com/35148959/63553034-eb4dea00-c4fe-11e9-961f-203c06997a73.png">


Just after the first breakpoint when wizard breaks to mobile view

<img width="1087" alt="Screen Shot 2019-08-22 at 5 03 55 PM" src="https://user-images.githubusercontent.com/35148959/63553045-ee48da80-c4fe-11e9-8946-68b4c0b4ca89.png">

Mobile view

<img width="793" alt="Screen Shot 2019-08-22 at 5 04 02 PM" src="https://user-images.githubusercontent.com/35148959/63553051-f0ab3480-c4fe-11e9-89d8-f93c851b2079.png">

Default behavior when viewport is shorter than the wizard navigation height, the wizard navigation will scroll. Do we want to retain this behavior, or should the whole content area scroll so that the wizard nav + content scroll together if either exceed the viewport height?

<img width="1420" alt="Screen Shot 2019-08-22 at 5 06 33 PM" src="https://user-images.githubusercontent.com/35148959/63553155-35cf6680-c4ff-11e9-998d-71a456c76d9b.png">

**Comment by matthewcarleton** [comment]
@mcoker this looks awesome! 
I'd say we'd never include the header. We get that from the page layout as you've shown here so it shouldn't be needed.

I wonder if at smaller viewport widths we should reduce the space that the side nav takes up. There's a lot of white space there. 

I'd say for shorter viewports the whole thing would scroll rather than just the side. This seems more reasonable, the user would have a larger area to scroll the content.

**Comment by matthewcarleton** [comment]
ah right, sorry that jogs my memory of when you mentioned this before.
Could we also consider something like `vw` and a min-width rather than a fixed value?  I don't feel strongly about it, so if @kybaker says 250px I'm cool with that too.

**Comment by kybaker** [comment]
@mcoker @matthewcarleton We did decide to go narrower because we do not have to follow the conventions set by the primary nav which uses that space to align elements. I would prefer making it as narrow as possible and still accommodate a reasonable number of characters. I think we could go to 175-200 and still be safe.
