### ISSUE TITLE
"Label" component looks like a button - confusing

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-next#2097]
The label component looks just like a button. This is confusing. 
![Xnip2019-07-24_09-59-47](https://user-images.githubusercontent.com/23172038/61799815-c9771f80-adf9-11e9-9194-27de9f262011.jpg)

**Comment by mceledonia** [comment]
Here is a concept I was exploring with work on the topology component. I think this would work with or without icons, but this was designed to include icons. My thoughts below:
- Keeping the area of the color behind the text background allows us to avoid accessibility concerns (having to ensure contrast of text on a variety of background colors) 
- Border effect gives labels a unique feel in the system (re: this issue) and provides a goldilocks visual weight... not too heavy, not too light. 
- Works with or without icons, I'd think without icons you can cut the width of the left-hand side in half
- Additional few pixels of height (which also allows the color background to extend behind the text background) provides extra room for fitting our 18px standard icon size, otherwise the icon would be too big for the standard background height.

![image](https://user-images.githubusercontent.com/30935938/61803634-89676b00-ae00-11e9-885a-edf65bb8002c.png)

https://marvelapp.com/41jgfd4

**Comment by rachael-phillips** [comment]
Thanks for opening and working on this @katierik and @mceledonia. @mcarrano making you aware of this one. What are your thoughts on this?

**Comment by rachael-phillips** [comment]
@katierik if we decide to move forward with this change how urgent would this be for you?

**Comment by mcarrano** [comment]
I agree with the need to visually clarify the difference between labels, chips, tags, and buttons. There is a related issue here that is assigned to @kybaker . https://github.com/patternfly/patternfly-next/issues/1837 I'd like to just make sure we are coordinating these updates. Let's figure out timeline requirements first.

**Comment by katierik** [comment]
We would like to have this for an Oct release

**Comment by rachael-phillips** [comment]
Thanks for the update @katierik !

**Comment by mcarrano** [comment]
I have opened a new issue in the patternfly-design repo here to track Label issues: https://github.com/patternfly/patternfly-design/issues/751  Closing this one as a duplicate.
