### ISSUE TITLE
Compact pagination variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2110]
In exploring Toolbar usage with product teams, it becomes clear that a compact pagination solution is needed when a pagination control needs to be placed in a toolbar above a list or table, The current Pagination component takes too much horizontal space making it difficult to fit all elements on a single line even at typical laptop viewport widths of 1440px. This problem is well illustrated through the mockups shown here: https://marvelapp.com/project/4205050/

This issue would create a new variant of the Pagination component that can be used in a toolbar when space becomes a consideration.

cc: @LHinson @rachael-phillips

**Comment by rachael-phillips** [comment]
Hi @mcarrano I will add this to our component status spreadsheet

**Comment by rachael-phillips** [comment]
Hi @mcarrano what do you think the priority of adding this enhancement is? Are products currently in need of this feature sooner rather than later?

**Comment by jeperry** [comment]
cloud.redhat.com apps would benefit from this ASAP @katierik @Rohoover  @KendraMar 

I'm wondering if instead of a variant, if this should just be an enhancement to the existing pagination.

**Comment by Rohoover** [comment]
@jeperry Agreed.

When I look at something outside of cloud.redhat.co like Cloudforms or Satellite, they would also prefer a compacted version.

**Comment by mattnolting** [comment]
https://deploy-preview-2126--pf-next.netlify.com/components/OverflowMenu/examples/ and
https://deploy-preview-2119--pf-next.netlify.com/components/DataToolbar/examples/ explore a method to hide/expose toolbar elements at different breakpoints. All "extra things" are hidden by default, then at a the desired breakpoint, they become visible with `pf-m-reveal-on-{breakpoint}`. In the case of pagination elements, a similar pattern could be `pf-m-reveal-on-{breakpoint}`, but placed on the element rather than the parent `.pf-c-pagination`.

Example:
```
.pf-c-pagination > .pf-c-options-menu.pf-m-reveal-on-md
.pf-c-pagination > .pf-c-pagination__nav.pf-m-reveal-on-xl
```

`.pf-c-pagination__total-items` could be visible until any other element is made visible. So, `__total-items` is the default visible element.

I'm not sure the pagination component should have baked in visible/hidden states, but rather control of the states should be controlled by modifiers seems like a better approach.

**Comment by mcarrano** [comment]
@mattnolting so are you saying that we would treat pagination like an Overflow menu and progressively disclose pieces at different breakpoints? Wasn't sure what you are suggesting.

**Comment by mattnolting** [comment]
@mcarrano on second thought, it think it makes sense just to have a compact version for the header. Otherwise we'll be constantly adjusting other toolbar elements to accomodate this. Would be an enhancement. Maybe just `<` and `>`?

**Comment by KendraMar** [comment]
Woohoo! Thanks again, guys. We have been wrestling constantly with what to do with crowded toolbars. This is a big help.
