### ISSUE TITLE
Card enhancement

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-next#2128]
Currently, the card view is missing two states

1. selected
2. disabled

here is a suggestion how design can look like and how we have implemented it so far. 

<img width="819" alt="Screen Shot 2019-08-05 at 09 48 11" src="https://user-images.githubusercontent.com/36040135/62447668-28c42080-b766-11e9-8f29-4a8d928a2884.png">

We already have both use cases being used in Cloud Services. 
[active](https://github.com/RedHatInsights/frontend-components/pull/109)
[disabled](https://github.com/ManageIQ/catalog-ui/pull/220)

**Comment by Hyperkid123** [comment]
We could definitely use some guidelines for these states.

**Comment by rvsia** [comment]
I would like to also talk about hovered state of the card:

![hnus](https://user-images.githubusercontent.com/32869456/62459931-db08e180-b780-11e9-82a3-b8e644930337.gif)

Right now, it looks like that ^^ The hover effect is too big in our case and it touches the other cards.

We would like to see some more decent effect, eg.: 

![krasa](https://user-images.githubusercontent.com/32869456/62459995-0d1a4380-b781-11e9-90f0-c353a466307d.gif)

@Hyperkid123 @terezanovotna

**Comment by Hyperkid123** [comment]
@rvsia we decided not use the hover effect at all because it was too aggressive.

**Comment by rachael-phillips** [comment]
@kybaker and @mcarrano what are your thoughts here design wise?

**Comment by mcoker** [comment]
I've also had products ask about the "accent" variation of a card that creates a blue border at the top of the card. @kybaker do you think that's something we should offer in PF4?


<img width="286" alt="Screen Shot 2019-08-12 at 9 56 58 AM" src="https://user-images.githubusercontent.com/35148959/62874888-9bde1180-bce7-11e9-9b51-68f5e057d191.png">

**Comment by lboehling** [comment]
I have been working on some design explorations for Apicurio in which clicking on a card in card view activates a slide-out drawer that shows more high level details about the card (similar to how google drive shows details/previews). This would also require showing an active state on the entire card that's clicked. I explored using the existing 3px top border from PF3 to indicate the active card (since we also use this blue border to show active tabs, expanded dropdowns, etc.) 

Currently apicurio uses a light blue fill on the card instead of check boxes for card select. If the blue top border alone isn't noticeable enough to show a card being active, could the blue fill also be used in conjunction with it? 

<img width="724" alt="Screen Shot 2019-08-16 at 11 47 18 AM" src="https://user-images.githubusercontent.com/46571616/63180819-09a67800-c01d-11e9-80bb-8ae165e78a10.png">

<img width="1424" alt="Screen Shot 2019-08-16 at 11 47 57 AM" src="https://user-images.githubusercontent.com/46571616/63180823-0a3f0e80-c01d-11e9-82bb-b2fd449a45bf.png">

**Comment by kybaker** [comment]
@mcoker I don't see an issue with making that border option available. 

@lboehling This was an issue we struggled with in PF3. The primary issue with using a blue background was ensuring there is a high enough level of contrast between the card and its content. It also will interfere with icons, charts, logos and other graphical elements. One possibility is to use various outline weighs and colors.

**Comment by mcarrano** [comment]
@lboehling I think we can easily build what you are proposing by using the Drawer component and populating it with object details. One thing I ask you to consider is what will happen if the user opens the Notification drawer at the same time this details panel is open?

**Comment by terezanovotna** [comment]
@mcarrano our use case is much more simple - there is no need for a drawer in the card. 
@lboehling thanks for sharing different examples with blue selects!

**Comment by rvsia** [comment]
What's the status? :question:

**Comment by mcarrano** [comment]
@terezanovotna After discussion with @kybaker and @mcoker we have decided that changes to the current card design for PF4 are not needed. Selection in a card view will be indicated by placing a checkbox on the upper right corner of each card as shown in the documentation here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/card-view  The blue selection border that existed in PF3 designs will not be supported. We're not clear what it means to "disable" a card. Disabled states should be handled by disabling any actions that live within the body of the card, only. Let us know if you need any advice about how to best migrate any existing designs to PatternFly 4.

@lboehling regarding the use of a sliding drawer to display object details when clicking on a card, I agree this could be useful but it addresses a different use case. If this is something needed by product, I recommend opening a new issue to request that we create a demo of this. It should be possible to build using existing PatternFly 4 components.
