### ISSUE TITLE
Select typeahead does not scale input with component width

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-next#2130]
With Select's input field it does not scale depending on the component size. Meaning that on smaller sizes it's easier to click the input on smaller sizes than bigger ones.

Images with input field highlighted:
![small size](https://user-images.githubusercontent.com/6598829/62527656-dd7c4180-b83b-11e9-87cc-aaa1fbcd7a71.png)

![big size](https://user-images.githubusercontent.com/6598829/62527680-ecfb8a80-b83b-11e9-9786-0890bd216880.png)

**Comment by rachael-phillips** [comment]
Hi @SpyTec what is the priority on this issue for you?

**Comment by rachael-phillips** [comment]
@mcarrano @kybaker what is your feedback design-wise on this issue?

**Comment by SpyTec** [comment]
> 
> 
> Hi @SpyTec what is the priority on this issue for you?

Hopefully low. Can't say I know how users would react or click generally - but we did notice this on our first demo with PF4

**Comment by rachael-phillips** [comment]
HI @SpyTec thanks so much for filing and letting me know. What is your timeline for this enhancement?

**Comment by mcarrano** [comment]
@mcoker can you take a look at this and comment? I would expect the width of the input field to scale to size of the component. Any reason it does not?

**Comment by mcoker** [comment]
I believe it was because we weren't sure how to have the input scale properly in the multiple typeahead variation when there are multiple chips in the typeahead, ensuring the text input scaled properly beside/underneath the chips.

That said, at a minimum I think we could add this enhancement to the single typeahead fairly easily. And I think we could come up with a solution for the multiple typeahead as well.

I mocked up a couple of examples. WDYT?

Regular typeahead: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35148959/62950594-f5a90f00-bdad-11e9-89bf-a082d24e7d72.gif)

Multiple typeahead:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35148959/62951453-a8c63800-bdaf-11e9-98b0-23d26bd8d348.gif)

**Comment by mcarrano** [comment]
Looks like you are on the right track @mcoker . So would this just require a Core fix or does it also involve React changes? I think we should get this in when we can as long as it does not involve breaking changes.

**Comment by mcoker** [comment]
@mcarrano I think we can do it in core. I'll go ahead and prioritize it.

@rachael-phillips for awareness
