### ISSUE TITLE
Dark nav Opt-in

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-next#2192]
Relevant blog post: https://blog.patternfly.org/patternfly/how-do-different-patternfly-visual-themes-affect-navigation-performance-perception-and-preference/

Latest Visuals: https://marvelapp.com/44473d5/screen/60826913
sketch file: [PF-DarkNav-8:2019.zip](https://github.com/patternfly/patternfly-next/files/3556936/PF-DarkNav-8.2019.zip)

**Comment by lboehling** [comment]
Hi @mcoker! 

Here is a link to the updated grayscale colors and nav specs: https://marvelapp.com/44473d5/screen/60826913

I'd suggest using the new PF-850 for the horizontal nav in mobile view too :)

**Comment by mcoker** [comment]
@lboehling thanks! Questions below:

In these 2 screenshots, what about this space at the top between the header and the first nav link? Is that OK, or do you want to make adjustments? 

<img width="700" alt="Screen Shot 2019-08-30 at 4 42 34 PM" src="https://user-images.githubusercontent.com/35148959/64052719-33938a80-cb45-11e9-8528-2f2f29400bd3.png">

<img width="618" alt="Screen Shot 2019-08-30 at 4 45 48 PM" src="https://user-images.githubusercontent.com/35148959/64052848-ae5ca580-cb45-11e9-97c4-33ef15d09f2b.png">

----

What about the section/group titles here? They currently match the link color text. Should that be updated to differentiate titles from links?

<img width="632" alt="Screen Shot 2019-08-30 at 4 47 06 PM" src="https://user-images.githubusercontent.com/35148959/64052913-d0eebe80-cb45-11e9-9b91-182ec602323d.png">

----

Since the divider color is the same as the nav background color, what color should the divider be when it's not used in a nested sub-menu in expandable nav? I made the divider white here to show where it would go.

Also do we want to limit the width of the divider so that it doesn't extend all the way to the right of the nav as it does currently? Assuming so, aligning the divider in an expandable nav nested sub-menu seems straight forward, but what should the width be when used between expandable sections? Should the divider extend underneath the arrow to the right, for example?

<img width="705" alt="Screen Shot 2019-08-30 at 4 49 19 PM" src="https://user-images.githubusercontent.com/35148959/64052999-317dfb80-cb46-11e9-9474-ff1b30b19223.png">

You can preview these changes here - just scroll down to see all of the examples: https://patternfly-next-pr-2197.surge.sh/demos/Page/examples-full/

**Comment by lboehling** [comment]
Hi @mcoker ! I’ll try my best to answer these questions. @kylebaker could you weigh in if you have different opinions?

 > _In these 2 screenshots, what about this space at the top between the header and the first nav link? Is that OK, or do you want to make adjustments?_


I think it would be nice to have the expanded bkg extend to the top of the nav when an expanded section is in the first row. Otherwise, I don’t think this is a huge deal. 

> _What about the section/group titles here? They currently match the link color text. Should that be updated to differentiate titles from links?_

This is a good question. I would suggest always keeping these white (I think in the screenshot is the pf-black-300 #D2D2D2 used for non-selected links). otherwise we could think about making the group titles light blue (as long as it’s always on the dark bkg pf-black-850, it should pass for accessibility) but I’m worried about using the blue text link style for something that isn’t a link.

<img width="410" alt="Screen Shot 2019-09-03 at 12 01 37 PM" src="https://user-images.githubusercontent.com/46571616/64190923-68edf000-ce45-11e9-92a9-d3ad2855f541.png">

> _Since the divider color is the same as the nav background color, what color should the divider be when it's not used in a nested sub-menu in expandable nav?_

I would use PF-Black-700 for the dividers outside of the expanded section. 

> _Also do we want to limit the width of the divider so that it doesn't extend all the way to the right of the nav as it does currently? Assuming so, aligning the divider in an expandable nav nested sub-menu seems straight forward, but what should the width be when used between expandable sections? Should the divider extend underneath the arrow to the right, for example?_

Also a good catch and question! I think we should follow the width of the divider lines in the PF4 light nav, which both extended all the way to the right of nav, fo both the nested divider and the divider between expandable sections. I’ll update the mocks to reflect this. 

<img width="404" alt="Screen Shot 2019-09-03 at 12 16 08 PM" src="https://user-images.githubusercontent.com/46571616/64190976-7c995680-ce45-11e9-8108-644a9793fdc2.png">

**Comment by mcoker** [comment]
@lboehling thanks! I've made the group titles white and updated the divider colors. https://patternfly-next-pr-2197.surge.sh/demos/Page/examples-full/

re: the issue with the first expandable item's background color not extending to the top of the nav, here I've just increased the top padding for the first expandable item, then used a negative margin the same value as the padding I added to offset that padding and to move the item up so it covers that gap at the top of the nav. That works, but it feels a little odd since the top padding for the first item doesn't match the item(s) below it.

<img width="706" alt="Screen Shot 2019-09-03 at 6 07 23 PM" src="https://user-images.githubusercontent.com/35148959/64214351-ca2db780-ce75-11e9-9f68-2777e4cf5d65.png">

Here's what it looks like if I add the same top padding to the rest of the expandable items in the nav list, which looks pretty bad since there is too much top padding compared to the bottom padding.

<img width="747" alt="Screen Shot 2019-09-03 at 6 00 16 PM" src="https://user-images.githubusercontent.com/35148959/64214290-85a21c00-ce75-11e9-8980-23d7f0f68d47.png">

WDYT?

**Comment by rachael-phillips** [comment]
@lboehling and @kybaker what do you think about Michael's comment above?

**Comment by mcoker** [comment]
@rachael-phillips thanks! I followed up with Lucia this morning and we sorted through the details. The latest is up on the PR preview - https://patternfly-next-pr-2197.surge.sh/demos/Page/examples/

**Comment by rachael-phillips** [comment]
That's great! Thanks @mcoker !
