### ISSUE TITLE
Attribute-Value (aka TextBox) filter demo

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2218]
Introduce a demo to show an Attribute-Value Filter in a toolbar. This should demo the designs documented here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#attribute-value-textbox-filters

**Comment by bmignano** [comment]
Per a discussion with @mcarrano and @rachael-phillips , I think it could be helpful to create a demo of this filter demonstrating examples with and without filter chips. The expected behavior is detailed below.

1. **Without chips**: The attribute value filter can be used to apply only one filter at a time. If the user switches the attribute, the original filter is cleared. In this case, the value selection is displayed at all times, making filter chips unnecessary.
2. **With chips**: The attribute value filter can be used to apply multiple filters at a time. Upon selecting or typing in a value, a filter chip will be created with the attribute-value pairing. Switching the attribute and filtering by a new value will create a new group of filter chips.
