### ISSUE TITLE
Add input group examples with plain button modifier

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2299]
We need to add examples to the input group component that show how to use a plain button in an input group

<img width="483" alt="Screen Shot 2019-09-24 at 9 40 50 AM" src="https://user-images.githubusercontent.com/35148959/65521788-69f7c780-deaf-11e9-83a6-59b02d315d64.png">

@mcarrano can you tell us which examples we should add? Ie, should we just add the example above, or would you like to see something else, more examples, etc?

**Comment by mcarrano** [comment]
Good question @mcoker . I think the example above is a good one, however I'm concerned that this might be misleading since we just decided to use the input button styling for the search field in the Attribute-Value Filter demo. Do you think I should look for a different example or is it good to reuse the same example and show two ways to implement this?

**Comment by mcoker** [comment]
If you think this example is fine and don't have a better example that might illustrate when you would want to use a plain button, I think the example above is fine.
