### ISSUE TITLE
Fix followup site refactor issues

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-next#2343]
These issues were identified by @mattnolting on 08-10-2019:
- [x] Example styles disappear on page reload when URL has a trailing slash
- [x] Sass is not live recompiled
- [x] Workspace uses patternfly version in gatsby-theme-patternfly-org rather than the local version

These issues were identified by @christiemolloy in #2242 :
- Merge example changes from #2318
- Chip group spacing
- Split button spacing
- Form component spacing
- Change mdxDefault.js background to same white as mdx.js
- Component variables page styling
- Fix component scaffolding in build/blueprints/*

**Comment by mcoker** [comment]
* "CSS Variables" text should be an h2.ws-title
* I think there is too much padding between the top section (with the component title) and the examples section below it
* Should .ws-section have a declared background color? Or can we use the grey background that comes from pf's page component?
* Should the first/title section have a white background?
* The example card header/footer border is too light. Can we use the pf4 divider component there, or at least define the border-color as `--pf-global--BorderColor--100`?
* full page demo links ("full page mode" link text) should open in new window (target="_blank")
* Just a personal suggestion - we could use a mustache icon instead of the "HBS" text below examples. Everyone loves a mustache 😁

---

#### Here's a screenshot of the first/title section of a page having `.pf-m-light`, the `background-color` removed from `.ws-title` (so the page component's default backgrounds apply), and the bottom padding of the first section adjusted

<img width="2490" alt="Screen Shot 2019-10-07 at 2 44 39 PM" src="https://user-images.githubusercontent.com/35148959/66344632-f4aade80-e913-11e9-996b-3a259734bdf8.png">

**Comment by rachael-phillips** [comment]
Hi @redallen and @mcoker for features like the HBS or mustache icon what will become of them on the workspace once we make the switch? We do not currently offer this documentation on the site.

**Comment by redallen** [comment]
Yes @rachael-phillips everything you see (minus the top and sive navigation) is a part of what will appear on patternfly.org when we make the switch.

Is this wanted or unwanted for patternfly.org?

**Comment by rachael-phillips** [comment]
Hi @redallen that's good to know, thank you. We will need to do an evaluation once @dgutride returns to understand which of these features would be ready for patternfly.org. The last time we talked about bringing any other features in than what currently appears on the PatternFly site, the answer was no.
