### ISSUE TITLE
TextArea resize modifiers name and descriptions are confusing

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-next#2374]
The TextArea resize modifier names and descriptions are confusing.  
`.pf-m-resize-vertical` has the description `Modifies a <textarea> element to resize vertically.` . which implies that in order to resize vertically you need to apply the modifier.  When in actual fact, applying the modifier makes it so the TextArea can ONLY be resized vertically.  

Similarly the `.pf-m-resize-horizontal` has the description `Modifies a <textarea> element to resize horizontally.`

**Comment by mcoker** [comment]
The modifier name matches the CSS property/value pair for the variation. So `.pf-m-resize-vertical` applies `resize: vertical;`, and `.pf-m-resize-horizontal` applies `resize: horizontal;`. This also affords us the ability to apply `.pf-m-resize-both` and/or `.pf-m-resize-none` (plus any additional value supported by the `resize` property) as additional variations in the future with no sort of class name conflicts. More on the property here - https://developer.mozilla.org/en-US/docs/Web/CSS/resize

I think the name is fine assuming you know the `<textarea>` CSS you want to apply, since it a direct map to the CSS you would apply.

Can you suggest different modifier names and/or descriptions that you think would be more appropriate?
