### ISSUE TITLE
Empty state must work on either a white of gray backgound

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2406]
The analysis of empty state consistency across products showed that they are currently being used on both white and gray backgrounds: https://docs.google.com/presentation/d/14l3A2oLx6AEZIPijbWcBmaSRoqZfR2sLZqYgaO33tto/edit?usp=sharing

The current design is optimized for a white background only. Placing it on gray degrades required contrast ratio for accessibility. Want to update the text color and size for empty state per this document: https://docs.google.com/document/d/1QasVyycsYPVBRYslBA3v_udEjnqP0to4Y7Uw4IXTH6k/edit?usp=sharing

**Comment by mcarrano** [comment]
@mmenestr @mceledonia I created this new issue for updating the empty state to work on gray as well as white. Did we conclude about the appropriate text color for this? Can one of you update this issue to specify that?

@rachael-phillips @LHinson Is this something we can add to our next release?

**Comment by mmenestr** [comment]
Was going through my issues and saw that this was left unanswered, but has been resolved since.

With the creation of issue #2424 resulting in a change in grey background color and secondary text color, having an empty state on a white background or a grey background always passes accessibility standards. The empty state text color therefore remains what it used to be with the header being pf-global--color--100, and the body being pf-global--color--200.

@mcarrano I think this can be closed because of this!

**Comment by mcarrano** [comment]
@mmenestr thanks for bringing that to my attention. @mcoker is this just a duplicate of @2424 then? If so, I will close it.

**Comment by mcoker** [comment]
@mcarrano, yep @mmenestr is correct, this should be resolved when we update the global colors. I'm good with closing this one.

**Comment by mcarrano** [comment]
Thanks for the feedback. Closing...
