### ISSUE TITLE
Backdrop for modal 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#255]
This blurs the background of the entire screen and blocks content. This is required for the modal demo.

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual: @mceledonia (included in the modal story) 
- CSS: @srambach

**Comment by christianvogt** [comment]
I added modal blur, against the entire body, to my last component library and eventually removed it due to performance issues. This was experienced in chrome.

The larger the body, the bigger the performance hit. So a page with a large scrollable body vs a small constrained height body (ie viewport constrained) will have a bigger impact.

Worth investigating further.
