### ISSUE TITLE
Chip group: investigate right and bottom margin 

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#2560]
Right margin - we should look at what this achieves and see if there is a better way to do it that stays within our guidelines at a component shouldn't have outside margins.

https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/ChipGroup/chip-group.scss#L29

Bottom margin - this was to offset the bottom margin applied to chips (useful for when they wrap/stack) inside of a chip group, but the chip group class structure has since changed and it's now being applied to the outer and inner chip-group elements, causing a spacing issue with elements underneath a chip group.

<img width="637" alt="Screen Shot 2020-01-06 at 5 04 04 PM" src="https://user-images.githubusercontent.com/35148959/71855429-9920f600-30a6-11ea-9741-f9b95b450b8f.png">

**Comment by mattnolting** [comment]
Margining issues are a result of added styling due to the dynamic nature of chips. The total number of `chips` is unknown and therefore each chip needs extra space for visual separation. The current structure is difficult to control for several reasons.

- `.pf-c-chip-group` has to work seamlessly while being nested within itself as well as unnested
- Because lists are used, it's necessary to target `<li>`s instead of dedicated classes
- Accessibility suffers using nested `<ul>`s and this structure adds complexity

This example: https://github.com/patternfly/patternfly-next/pull/2607 updates custom property values, without constituting breaking changes. 

A refactor might look like this: https://codepen.io/bobcatTaco/pen/yLyGmqZ?editors=1100

A couple of features in this approach:
- `chip-group`s are `<div>`s instead of `<ul>`s
- Each element has a dedicated selector `chip-group`, `chip-group pf-m-toolbar`, `chip-group__label`, `chip-group__list`, which makes them easy to style.

Accessibility audit (for nested chip groups):
- Current structure announces, "List, two items"
- Refactored structure announces, "list Chip group with nested groups 3 items 3 sublists"

**Comment by mattnolting** [comment]
Current structure:

**Simple unnested list**
**VO announces** - list two items
```
<ul class="pf-c-chip-group">
  <li class="pf-c-chip">
    <span class="pf-c-chip__text">Chip one</span>
    <button class="pf-c-button pf-m-plain" type="button">          
      <i class="fas fa-times-circle" aria-hidden="true"></i>        
    </button>      
  </li>
  <li class="pf-c-chip">
    <span class="pf-c-chip__text">Chip two</span>
    <button class="pf-c-button pf-m-plain" type="button">          
      <i class="fas fa-times-circle" aria-hidden="true"></i>        
    </button>      
  </li>
</ul>
```

**Nested list**
**VO announces** - list two items (same as a simple list)
```
<ul class="pf-c-chip-group pf-m-toolbar">
  <li> <-- this is problematic -->
    <h4 class="pf-c-chip-group__label">Label</h4>
    <ul class="pf-c-chip-group">
      <li class="pf-c-chip">
        <span class="pf-c-chip__text">Chip one</span>
        <button class="pf-c-button pf-m-plain" type="button">          
          <i class="fas fa-times-circle" aria-hidden="true"></i>        
        </button>      
      </li>
      <li class="pf-c-chip">
        <span class="pf-c-chip__text">Chip two</span>
        <button class="pf-c-button pf-m-plain" type="button">          
          <i class="fas fa-times-circle" aria-hidden="true"></i>        
        </button>      
      </li>
    </ul>
  </li>
</ul>
```

**Comment by mattnolting** [comment]
Refactored structure 

**Simjple list**
**VO announces** - list two items

```
<div class="pf-c-chip-group">
  <h4 class="pf-c-chip-group__label" aria-hidden="true" id="example1-title1">Simple chip group example</h4>
  <ul class="pf-c-alt-chip-group__list" aria-labelledby="example1-title1">
    <li class="pf-c-chip">
      <button />
    </li>
    <li class="pf-c-chip">
      <button />
    </li>
  </ul>
</div>
```

**Nested list**
**VO announces** - list Nested chip group example 3 items 3 sublists

```
<div class="pf-c-chip-group" role="list" aria-label="Nested chip group example">
  <div class="pf-c-chip-group pf-m-toolbar">
    <h4 class="pf-c-chip-group__label" aria-hidden="true" id="title1">Category A</h4>
    <ul class="pf-c-chip-group__list" aria-labelledby="title1">
      <li class="pf-c-chip">
        <button />
      </li>
      <li class="pf-c-chip">
        <button />
      </li>
    </ul>
  </div>
  <div class="pf-c-chip-group pf-m-toolbar">
    <h4 class="pf-c-chip-group__label" aria-hidden="true" id="title2">Category B longer title</h4>
    <ul class="pf-c-chip-group__list" aria-labelledby="title2">
      <li class="pf-c-chip">
        <button />
      </li>
      <li class="pf-c-chip">
        <button />
      </li>
    </ul>
  </div>
</div>
```

**Comment by mattnolting** [comment]
Closing in favor of #2694
