### ISSUE TITLE
Add filtering to checkbox select menu

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#2565]
Want the ability to filter items in a checkbox select component. This is useful when the list of potential options is very large.

Here is the target design:

![Checkbox (without badges)](https://user-images.githubusercontent.com/6619860/72019956-acfc6180-3238-11ea-9b6d-247e81869e1a.png)

This takes the existing checkbox select and adds a type-ahead filter and an optional Clear button. The clear button, when present, will clear any existing selections. If nothing selected, the clear button should be hidden.

**Comment by mcarrano** [comment]
@bmignano I've opened this issue following conversation with Zac and @jcaianirh working on a new search page for Openshift. The request was to add filtering to a checkbox select to quickly select resources from a potentially long list of options as shown in this design: http://openshift.github.io/openshift-origin-design/admin-perspective/future-openshift/search/search

Can you confirm that this is what you would expect? Wasn't sure if the Clear button is needed for your application, but I know that this is something that was discussed earlier with you and @serenamarie125 .

**Comment by jcaianirh** [comment]
@mcarrano thanks for the fast turnaround. this is awesome!

**Comment by bmignano** [comment]
@mcarrano Thanks, this looks great to me! I'm not sure that a Clear button is needed in this context. I'd expect the textbox filter to behave like any other textbox filter in a toolbar, which at least in OpenShift do not have a clear functionality. Also, since it's a dynamic filter (i.e., it searches the list as you type), it seems unnecessary to me. Open to hearing other opinions though!
