### ISSUE TITLE
DataToolbar pagination has margin right

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-next#2631]
When there's a `Pagination` in the `DataToolbar` that's aligned to the right, it will still have a `margin-right` from being a child of `DataToolbarContent`. This makes it so it is not aligned to pagination that's below the table.

See
![image](https://user-images.githubusercontent.com/6598829/73258844-d7519700-41c6-11ea-8e51-daafbc68a0af.png)

and
![image](https://user-images.githubusercontent.com/6598829/73258873-e6384980-41c6-11ea-8e29-58498894e66d.png)

Also happens in React Docs: https://www.patternfly.org/v4/documentation/react/experimental/datatoolbar#stacked-example

**Edit:** There is also a padding on `DataToolbar` itself which also inflates the mis-alignment

**Comment by mattnolting** [comment]
This issue was addressed in Core https://github.com/patternfly/patternfly-next/pull/2460 by adding `<div class="pf-c-data-toolbar__content-section">` to `<div class="pf-c-data-toolbar__content">` to separate dynamic (`.pf-c-data-toolbar__expandable-content') and static elements. I thought we had addressed this in React as well, but it appears Core and React are out of sync.

**Comment by mattnolting** [comment]
Moving to React: https://github.com/patternfly/patternfly-react/issues/3614
