### ISSUE TITLE
Investigate: dropdown -> dropup when at end of page or end of table

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly-next#2647]
- The last two/three action menus in tables often break out of the page container. 
- Pagination bottom dropdown often breaks out of page section

Both examples are visibility/accessibility issues. 

![image](https://user-images.githubusercontent.com/5385435/73546552-6e0e9580-440b-11ea-993b-530e8606a6e7.png)

**Comment by SpyTec** [comment]
Do we have a way to manually override this? I've been trying to apply styling to the page but without success.

At a glance I suspect it's an issue of grid display and absolute elements since the grid becomes scrollable. Using `overflow` or `z-index` has no effect, nor can I make it drop up due to it being in a PF4 React Table.

**Comment by mattnolting** [comment]
In core, nothing is self-aware as we can't use JS. [Popover] (https://patternfly-react.surge.sh/documentation/react/components/popover) has already figured this out. The issue should be resolved in a similar way to `pf-c-popover`. Need to move to react. 

Having said that, this issue exposes and bug. The footer pagination dropdown needs to be a `.pf-c-dropdown.pf-m-top` [2726](https://github.com/patternfly/patternfly-next/issues/2726)

**Comment by mattnolting** [comment]
Issue moved to [patternfly/patternfly-react #3784](https://github.com/patternfly/patternfly-react/issues/3784) via [**ZenHub**](https://www.zenhub.com/)
