### ISSUE TITLE
Define new branch strategy around breaking changes

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-next#2671]

**Comment by redallen** [comment]
Thoughts on cutting a `breaking-change` branch off of patternfly-next? PRs can still be opened on patternfly-next, but instead of asking to merge into master you can select to merge into the breaking-change branch:
![image.png](https://images.zenhubusercontent.com/5cb4eb924103d93ceadefd64/4a1b5469-71cf-4d48-9952-e3abb620c1c3)

If we need prereleases on a different release channel, that can be configured.

**Comment by redallen** [comment]
We're all set for Core and React.

Check out https://github.com/patternfly/patternfly-next/pull/2771 and https://github.com/patternfly/patternfly-react/pull/3868. We have a new `v4` branch that releases to npm on `prerelease-v4` and has the same CI and branch protection rules as `master.
