### ISSUE TITLE
Add support for plain inline buttons

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-next#2719]
#### SUMMARY
Button Variations: https://www.patternfly.org/v4/documentation/react/components/button#variations

The button prop `isInline` currently doesn't play well with `variant="plain"`.  In the example below, the DataListAction contains a plain button, but it adds about 10px of whitespace to the row height. 

Changing the button variant to `link` and adding `isInline` removes the extra whitespace, but we don't want the "link" styles. Could you add support for a "plain" "inline" button?

##### Plain 
<img width="501" alt="Screen Shot 2020-02-13 at 4 23 12 PM" src="https://user-images.githubusercontent.com/15881645/74479547-56102a80-4e7d-11ea-9fa5-52e5f4bd0fec.png">

##### Link and Inline
<img width="447" alt="Screen Shot 2020-02-13 at 4 22 47 PM" src="https://user-images.githubusercontent.com/15881645/74479534-527ca380-4e7d-11ea-918b-b12c3037d222.png">

**Comment by marshmalien** [comment]
cc @trahman73

**Comment by mcoker** [comment]
@marshmalien after looking at this some more, it looks like this is due to a bug in the react component. I opened a react issue for this yesterday https://github.com/patternfly/patternfly-react/issues/3860

The basic idea is that in core, we have a `<div class="pf-c-data-list__action"></div>` element that we use to wrap the plain button actions, and that class offsets the spacing of the button so that it better aligns with the row and doesn't push content down. That class wasn't implemented in the react component, resulting in this visual bug. You can see that class in use in core by going to the [data list examples page](https://www.patternfly.org/v4/documentation/core/components/datalist) and inspecting a row that has a kebab icon used for the dropdown action of a row.

Could you add this element to your implementation of the data list temporarily until we're able to resolve the bug in react?

**Comment by marshmalien** [comment]
Great investigative work @mcoker. If there is a plan to add `.pf-c-data-list__action` to the data list action component then we can wait until the fix comes downstream. I would rather not locate and wrap every instance of our action buttons with a wrapper, only to remove it once this change lands.

**Comment by mcoker** [comment]
@marshmalien agreed! Is it OK if we close this issue and you can track this bug in https://github.com/patternfly/patternfly-react/issues/3860?

**Comment by marshmalien** [comment]
@mcoker Yes, sounds good to me 👍 Thank you for looking into this!
