### ISSUE TITLE
Remove padding around CardActions

### ISSUE THREAD

**Issue by marshmalien** [patternfly/patternfly-next#2724]
We use action buttons in the card footer component similarly to how the modal footer positions action buttons. The difference is that there is about 16px of left padding on the CardAction component which prevents the buttons from aligning flush to the left. By default, could we remove the left padding? 

<img width="400" alt="Screen Shot 2020-02-18 at 5 15 13 PM" src="https://user-images.githubusercontent.com/15881645/74783033-c00c4380-5272-11ea-8d60-804a2ee568cb.png">

**Comment by mcoker** [comment]
Hey @marshmalien, `<CardActions>` goes in `<CardHead>` and positions actions at the top/right of the card. You can see a demo of that here - https://www.patternfly.org/v4/documentation/react/components/card#with-image-and-actions

Since buttons in the footer of a card aren't a fundamental part of the card like they are actions associated with a modal, we don't have a layout to space actions in a card footer. If the actions in the card are associated with a form, you could use the form component and the `<ActionGroup>` component. Otherwise you could use the flex or split layouts (or custom CSS) to place a row of actions in the card.

Would one of those options work for you? We have a proposal for a generic action list component that would work in this use case that we could bump up in priority as well - https://github.com/patternfly/patternfly-next/issues/2021

**Comment by marshmalien** [comment]
The Master-Detail design layout gives us the option to place Details in a card, so I placed the actions in the card footer because that is where they're located in the modal 🤷‍♀ For this use case, a generic action list component would be perfect! Bumping up the priority would really help us out. Thank you @mcoker

**Comment by mcoker** [comment]
@marshmalien were you able to come up with a solution for now? Curious if we can close this and you can track the progress of the action list component via https://github.com/patternfly/patternfly-next/issues/2021. We should be able to slate work for that following the major version bump we're going to work on for the next few milestones.

**Comment by marshmalien** [comment]
Yes, we can go ahead and close this issue. We will swap our current card actions implementation when the [action list component](https://github.com/patternfly/patternfly-next/issues/2021) becomes available. Thank you!
