### ISSUE TITLE
Experimental/Tech Preview/Beta Feature 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#294]
Need a way to reflect that a specific feature in an app is Experimental/Tech Preview/Beta at a page or element level.

This issue is being kicked back to discovery to determine the idea design/technical approach. Need to determine if this is a demo or a component. In PF3, we supported an "experimental feture" pattern that included a colored frame around a page. A frame is harder to implement than say a flag indicating "experimental feature". Conversation should include what does and does not belong in pf-core. 

https://www.patternfly.org/pattern-library/communication/experimental-features/

**Comment by mindreeper2420** [comment]
A little background on Experimental Features:

The Experimental Features component originated as part of OpenShift.io, in order to identify what areas of the application were not considered to be a final release version. The original design called for applying a border/container around each piece that was experimental - whether that be the entire page, an individual component on a page, or as a barrier to entry (used in combination with the Empty State. As OpenShift.io progressed with the use of feature and different levels of access, this was adapted to be a Feature Flag component, with a new design and criteria for usage.

The Feature Flag component (design on [InVision](https://redhat.invisionapp.com/share/KAF97RBGB)) simplifies to display of a feature flag, while giving the user additional information that the original Experimental Features bar didn't provide. It also allows OpenShift.io to call out multiple levels on a single page, with the highest level (that being farthest from official release) as the primary callout and indicator.
![screen shot 2018-07-30 at 11 38 19 am](https://user-images.githubusercontent.com/4032718/43407573-13b966b6-93ed-11e8-9fee-22bea1f08086.png)

Currently in use, OpenShift.io utilizes this to primarily call out individual components on a page that have flagged features (such as a new module). For full pages hidden behind a flag, we use a modified Empty State component:
![screen shot 2018-07-30 at 11 40 58 am](https://user-images.githubusercontent.com/4032718/43407702-73a60b92-93ed-11e8-94ca-db3174ac18b1.png)

**Comment by mcarrano** [comment]
This need was raised during the PF Weekly meeting on July 25. A Google doc has been started here to capture requirements: https://docs.google.com/document/d/1AKodtar3NEJ0GEJDWwFsOfoR0c9x8XBnGa9UAF5byNI/edit?usp=sharing

**Comment by mcarrano** [comment]
Per discussion with @rachael-phillips and @LHinson , this one will be closed. We believe it is best addressed at the product level using existing PatternFly components.
