### ISSUE TITLE
Alerts and Notifications - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#299]
Introduce UX Guidelines for usage of alerts and notifications. The goal of this will be to advise designers on the use of alerts and notifications when applying in product. Topics to be considered should include:

- Elements of the notification system: inline alerts, toast alerts, modal alerts, and the notification drawer.
- Accessibility of alerts
- When to include actions in alerts
- Alert types
- Lifecycle of an alert/notification: persistence, acknowledging and clearing notifications; use of the notification drawer; linking to more details

**Comment by jgiardino** [comment]
Here are the [A11y recommendations for toast notifications](https://docs.google.com/presentation/d/1fs1jbOutlRFjITs7Qjo9gKscOOzuXv7t6b78GBrCc8g/edit?usp=sharing) based on our review with GMS participants and our own internal screen reader testing.

I know there are different opinions about whether Notifications should have actions (i.e. only include actions if the notification is implemented as a modal alert dialogs). If we do decide that actions can be included with toast notifications, then my recommendations would be:

- the actions are not included in the element with `role="alert"`
- any actions that are presented in the notification are redundant (i.e. that's not the only place where that action exists, and it can be found elsewhere)

In my opinion, that last bullet is kind of analogous to using color to indicate alert type. We use color even though not all users can perceive the color, and that's ok, because the color is redundant to the other ways in which we communicate meaning (e.g. with icons and with screen-reader-only text).

Likewise, we include actions in a toast notification even though sr users can't perceive the actions when the message text is announced, and assume that's ok, because those actions can be accessed somewhere else in the UI. The problem with that is, they don't really know when actions _are_ included.

It could be argued that if we included actions in a notification, then additional screen-reader-only text should be included to communicate how to access the same actions that are included in the notification. For example, the sighted user experience could be:

> The build is ready. [Download](#)

And the screen reader user experience could be:

> The build is ready. Navigate to the "Builds" tab to download.

**Comment by mcarrano** [comment]
Here is a first draft of the design documentation for alerts and notifications, including the notification drawer. @jgiardino @LHinson @stacymcauliffe @rachael-phillips please feel free to review and comment. There is still more to do here, but wanted to get this out there to begin the review cycle.

https://docs.google.com/document/d/1UH6J2Mf1Nqx4zUx-TzO6MCgPFq6NJatRb0kagmGN5yE/edit?usp=sharing

@jgiardino I'm not sure that I've been able to address all of your accessibility concerns about notifications, but I think I'm now in a better position to talk more about this. Will set something up.

**Comment by mcarrano** [comment]
@LHinson @stacymcauliffe @rachael-phillips I have a more complete draft of this document here: https://docs.google.com/document/d/1UH6J2Mf1Nqx4zUx-TzO6MCgPFq6NJatRb0kagmGN5yE/edit?usp=sharing  I welcome any feedback or comments. The wireframe graphics are just placeholders and need to be replaced, but figured I'd wait on a content review first.

**Comment by rachael-phillips** [comment]
Thanks, Matt! I'm taking a look now!

**Comment by mcarrano** [comment]
Draft design doc has been updated after review by UX Leads, https://docs.google.com/document/d/1UH6J2Mf1Nqx4zUx-TzO6MCgPFq6NJatRb0kagmGN5yE/edit?usp=sharing

Move to queue for publishing.
