### ISSUE TITLE
Toolbar demo 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#347]
A toolbar demo should include: 
- Find
- Sort
- Filter 

**Find**
As of now, considering "Find" a demo as it should be built with components already introduced to PF. This will begin in the interaction design phase to revisit and improve design. If more components are required to build this, those issues need introduced. 
https://www.patternfly.org/pattern-library/forms-and-controls/find/#design

**Filter**
Introduce a Checkbox Filter component. See current design here: http://www.patternfly.org/pattern-library/forms-and-controls/checkbox-filter/#/design

Introduce a textbox filter component. See current design here: http://www.patternfly.org/pattern-library/forms-and-controls/textbox-filter/#/design

**Sort**
https://www.patternfly.org/pattern-library/forms-and-controls/sort/#design

Design folder: https://drive.google.com/open?id=1FlHGNY3OzRo1QmquTbC2YxQD0O1nRhjj

**Comment by mcarrano** [comment]
Have completed initial requirements gathering and concepts. Those are summarized here: https://docs.google.com/document/d/1BKUlaMN75Ui372fFowz9BPD7vFhq1w_IfxHi7C59oPo/edit?usp=sharing. I have sent this to the UX leads for feedback.

**Comment by mcarrano** [comment]
See the design folder for the latest requirements and wireframes. https://drive.google.com/open?id=1FlHGNY3OzRo1QmquTbC2YxQD0O1nRhjj

This includes a simple textbox filter, only. Because of the complexity of filter requirements, a separate demo has been defined to cover the various use case (#457) to allow this issue to move forward using a simplified approach.
