### ISSUE TITLE
Example of the PF3/PF4  HTML structure: Popover

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#418]
Create simple HTML files files to show the class structure differences between the popover for PatternFly 3 and PatternFly 4.

pf4: https://pf-next.com/components/Popover/examples/
pf3: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/popovers.html

**Comment by jameslau** [comment]
Had help from @christiemolloy and @mcoker about this issue. Later spoke with @matthewcarleton about migration issues for PF3 on a PF4 workspace and future website. Heavily dependent Bootstrap components and examples maybe an issue in the long run since it utilizes a lot of JavaScript in order to enable features. @matthewcarleton will ping @dgutride about this issue as well.
