### ISSUE TITLE
Spike: Explore avenues to update PF3 to better align with PF4

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#422]
This issue is a spike to explore ways we can update PF3 to better align with PF4. Some avenues include: 
- Evaluate how feasibile a PF4 theme is for PF3 
- Evaluate how we can provide new design updates for PF3 components 

This spike should also include a test page that mixes PF4 themed PF3 components with PF3 components.

**Comment by LHinson** [comment]
Removing this as CSS/Visuals issue for now. 

Current summary: 
- A PF4 theme for PF3 is likely not feasible and costly. 
- Improvements to PF3 would likely need to form of new components with new styling. 
- strategy still pending dependent on pf3 theme for pf4 feasibility and product insight.

**Comment by dgutride** [comment]
This makes sense @LHinson  - just to expand a little on those bullets:

- A PF4 theme for PF3 is likely not feasible and costly.
The PF3 theme options are limited to colors and would not give us enough flexibility to achieve a consistent look and feel without overriding many of the PF3 classes.  This is a non-starter because it's an immediate breaking change for consumers that have overridden initially.

- Improvements to PF3 would likely need to form of new components with new styling.
This conclusion was arrived at when we realized that in order to support the new look and feel, we'd be introducing breaking changes to components (structural changes are going to be necessary to use updated font sizes, provide accessibility or migrate to a responsive design).

- There is no technical reason/blockers for adding components to PF3 with PF4 styling.
PF4 doesn't overlap with PF3 naming in any way, so additional research to make sure this is feasible is not necessary at this time.

- strategy still pending dependent on pf3 theme for pf4 feasibility and product insight.
