### ISSUE TITLE
Introduce Login demo

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#43]
Introduce the login demo. 
[Working File](https://drive.google.com/open?id=1GIHUTU9iAXv6-coor0OcFRsFGfAx2yXs)
[PDF](https://drive.google.com/open?id=1Sf5h0rc-ym_8zjA8o11_xbgPWew3bzb3)

For this issue, the scope includes basic login only seen here: https://www.patternfly.org/pattern-library/application-framework/login-page/

Updated design folder with Visual/spec PDF here:
https://drive.google.com/open?id=1ElopIvkE-RDeqTpJQ2sCXjzXaIbhRafT

Component lifecycle: 
- [x] Interaction design requirements 
- [x] Visuals 
- [x] First checkpoint complete and approved 
- [ ] CSS 
- [ ] React
- [ ] Second checkpoint complete and approved 

Contacts: 
- IxD 
- Visual @mceledonia 
- CSS @mattnolting 

Related #407 #408

**Comment by mceledonia** [comment]
https://drive.google.com/open?id=1skXkOVsOD9mCvpNS8HfocLi7uwe-OzyO

**Comment by kybaker** [comment]
This login design combines the current PatternFly login design thinking while utilizing the new design system defined for Next. We increased the box size and left aligned to address an issue with the current login where the vector logotypes do not scale down well when the name is longer. This new layout also follows the golden ratio.

[Login Design PDF](https://drive.google.com/open?id=1Vp5Eh9IwAXYV_AkCqNqe7IGsPJMtGJwP)

**Comment by matthewcarleton** [comment]
@kybaker @mceledonia Is this design still in progress? I have questions about this but don't want to hinder progress if it's still a WIP.

**Comment by kybaker** [comment]
@matthewcarleton Now is a good time to ask questions. Michael and I did not want to create mockups for the responsive states until we talked to CSS.

**Comment by kybaker** [comment]
@mceledonia After meeting with @matthewcarleton the next step for this design is to incorporate the variations identified in the current login pattern. We also need to design the responsive states.

**Comment by mceledonia** [comment]
Updated design which includes Red Hat logo

[Working File](https://drive.google.com/open?id=1n3qV8j1WblY-p_oatRqjk4VN3_TtaCNM)
[PDF](https://drive.google.com/open?id=1B3irRl7Mb__GfBgwX2sPLI28RzGg5Wtt)

**Comment by matthewcarleton** [comment]
These are looking great @mceledonia. I have some questions but it can wait until you finish up.

**Comment by matthewcarleton** [comment]
@mceledonia and I talked these through. Once he is ready we can get these reviewed by the larger group.

**Comment by mceledonia** [comment]
Updated my last comment above with the latest versions

**Comment by mcarrano** [comment]
@mceledonia @kybaker These look great. Just one question. I see you are using input field styles with an underscore rather than a box. Is this special styling for the login screen, only, or will this be an alternate text box style available throughout?  Also, how will validation errors be shown? Same as the current design?

**Comment by LHinson** [comment]
@kybaker this issue requires an update of the spacing in the mockups to match box spacing before @mattnolting will take it to build the demo

**Comment by mcarrano** [comment]
This issue was recently filed against PF-3 https://github.com/patternfly/patternfly-design/issues/671 Should consider how validation errors will be displayed and how that affects spacing while doing this implementation.

**Comment by thomasmaas** [comment]
Any reason why we stick with "Log in" while the more common phrasing these days is "Sign in"? 
"Log in" feels a bit dated and more technical than needed.

**Comment by LHinson** [comment]
@stacymcauliffe any insight re: @thomasmaas feedback about wording?

**Comment by stacymcauliffe** [comment]
I'd support a switch to Sign in, although the industry is a bit split on which is better. I think the big concern is the potential confusion between "Sign In" and "Sign Up" which could be easily avoided with different copy around the sign up experience, like "Create an account" instead of "Sign up" for instance. 

Google, Amazon, and Microsoft are all using Sign in, whereas services like Facebook and Instagram use Log In.

Another reason I prefer Sign In is the "Log in" v "Login" issue, where "Login" is used as a noun and "Log in" is used for the action of actually logging in, which can become kind of a pain to keep straight.

**Comment by LHinson** [comment]
@mceledonia can we update the mock-ups to say sign-in vs log in?

**Comment by LHinson** [comment]
Closed by #665
