### ISSUE TITLE
Interaction Spec for Navigation

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#460]
Need to document/prototype interactions associated with the menu system defined in #207 .

This will feed JS implementation.

**Comment by mcarrano** [comment]
I have drafted an initial design page for Vertical Navigation. This includes guidance on usage and behaviors. You can find that here: https://github.com/patternfly/patternfly-next/wiki/Vertical-Navigation  I will plan to do similar pages for the Horizontal Primary Nav and the Tertiary Nav bar, but wanted to circulate this around to first get feedback about the form and content.

@LHinson @dmiller9911 @catrobson @stacymcauliffe @jgiardino please review and comment considering the following questions:

* Does this provide the level of information you would need to implement and/or use this feature?
* Does this tell you what the feature is a where it should be used (note that this content would be presented on the web in the context of working code examples. We want to get away from lots of static mockups where possible)?
* Does the format provide the right level of detail without getting too verbose (streamlining our docs is a definite goal)?
* Is there anything missing?

@stacymcauliffe It would be great to discuss what type of information we could include here about naming menu items. @catrobson and I were discussing use of the term "Overview" for example as a standard landing page name.

Also note, I've temporarily created this page in the Wiki within the patternfly-next repo since it was unclear where it belongs. @LHinson we should discuss this.

Thanks everyone!

**Comment by jgiardino** [comment]
I like the overall structure that you have outlined for the design documentation. Here are my answers to your questions:

- Does this provide the level of information you would need to implement and/or use this feature?
  - I like the table structure that you have. These additional details for design documents might also be good to include:
    - A column that includes the text label for the element when the text string is defined by PatternFly (or otherwise state that they are defined by the consumer). All elements should have a text label / accessible name, so this would be an easy way to enforce this accessibility requirement at the design stage. 
      - Whenever a row does indicate that the text string is defined by the user, then it might be good to have a similar table in the Content section that includes the Element column with the same element names, so that it's easy for consumers to match the recommendations to the element that's described in the Usage section.
    - What's the expected behavior for on_Hover/on_Focus events? For example, for accessibility, when the menu toggle is on hover or focus, a tooltip with the button label should display. But some elements might have other expected behaviors that are not obvious to the developer.
      - Related to this one, do we need to explain somewhere that on_Click in most cases is equivalent to the Enter keypress and Touch events?
  - From this design document alone, I don't know what the expectation is for all possible states. For example, what should the styles be when a primary menu item is collapsed and the current page is a child of that primary menu item? Or when a primary menu item is expanded and the current page is not a child of that primary menu item. 
- Does this tell you what the feature is a where it should be used (note that this content would be presented on the web in the context of working code examples. We want to get away from lots of static mockups where possible)?
  - Makes sense to me. 
- Does the format provide the right level of detail without getting too verbose (streamlining our docs is a definite goal)?
  - A recommendation I heard once on how to best communicate use cases to a developer is to phrase them in a "Given ... When ... Then ..." sentence structure. For example: 
    > When the user clicks the Menu Toggle, then the display of the menu is toggled.
    > Given the user is on a mobile device, when the user selects a menu item, then the menu is hidden.

    The explanation was that this is a better mapping to the logic a developer has to implement, and makes it easier for the developer to understand the requirement. I like the brevity that you have now, but there are still cases where it seems a little verbose where I think we can be more straightforward. I'm not sure that the GivenWhenThen style is the best fit for this document structure, but I think doing more to clarify the logic points would help.
- Is there anything missing?
  - I'll let you know if I think of anything else...

I like how you describe this as "site-wide navigation", but the label "Tertiary Navigation" seems really odd to me. I don't think we can assume that the component we label as "Tertiary Nav" is in fact the third level of navigation, because the consumer might be pairing this with a page in the vertical nav that's a Primary Menu Item with no children, which technically would make it a secondary nav? Maybe labeling it something like "page level navigation" would work better? This might work as a better umbrella term for Tabs, which we might want to include in the same design document. Having a single document that explains when you would implement page level nav as links vs as tabs might be good, because while they are visually similar, they are functionally and semantically different and serve different use cases, and consumers should understand that distinction.

**Comment by mcarrano** [comment]
I've made some minor changes in response to @jgiardino 's comments. @LHinson @dmiller9911 @jgiardino  please review here:

https://github.com/patternfly/patternfly-next/wiki/Horizontal-Navigation
https://github.com/patternfly/patternfly-next/wiki/Vertical-Navigation

Unless there are immediate changes that need to be made, I propose to close this out and address refinements within the context of the related React implementation issues. There is also still a need for a page that describes these components working together at the page level, but I believe this document is contingent on working through issues around how to present this on the website.
