### ISSUE TITLE
Progress Bar - Refinements and Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-next#580]
Introduce design documentation for the Progress Bar component and refine the examples to consider reflecting progress for step-wise user tasks as well as reporting progress for system tasks (i.e. tasks running in the background). 

* Refine examples and potentially remove any examples that we wouldn't recommend and/or clarify existing examples.

* Consider accessibility concerns and refine examples as needed address any concerns.

Related issue: #24

**Comment by jgiardino** [comment]
Hi @mcarrano,

@srambach and I were reviewing PR https://github.com/patternfly/patternfly-next/pull/648, and had a few questions:

1. Is the descriptive text above the progress bar meant to be dynamic or static? We assumed we would support both, since our [current PF3 examples](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/progress-bars.html) support both (e.g. the example labeled with "Downloading: Product Repositories" most likely changes to state what's being downloaded, whereas the one labeled "CPU" always says "CPU"). For screen reader support, we can either provide a numeric value in the form of `aria-valuenow`, or specific text string that describes the current status in the form of `aria-valuetext`, but not both (unless we incorporate the numeric value with the string).* For now, we decided to have all but the last example show a static text description of the progress bar, and will include an example at the end that illustrates how to provide a text string that describes the current progress state. But let us know if you have any suggestions for these patterns (especially regarding example text strings to use 😄).
2. Is the expectation that we would always show percentage as a value?
3. There is one example near the end where the value is not included in the form of text, labeled "Progress Without Measure". Since the other examples provide the progress value in text as well as the bar, we aren't as concerned with the color contrast of the bar itself. But this last example isn't accessible for low vision users (e.g. if progress is perceived by comparing the width of the dark blue to the width of the light blue, but the light blue isn't visible, then they can't assess progress). My question for you here is whether this is a pattern you want to support? If it is, then I'd suggest we revise the visual design to address low vision accessibility, at least for this one case (@mceledonia, @kybaker).


*I was testing in JAWS, which will ignore `aria-valuenow` if `aria-valuetext` is present. Other screen readers might have different behaviors.

**Comment by mcarrano** [comment]
@rachael-phillips Would you be interested in taking on documentation for this issue (instead of Breadcrumbs) since we already have completed examples here: https://pf-next.netlify.com/components/Progress/examples/ ?

The biggest challenge is that there are a large number of different example configurations for the progress bar, but no guidance on what to use and when. It may be that we don't need all of these options. See comment from @jgiardino above. We can discuss.

**Comment by rachael-phillips** [comment]
Here are the visuals that we will need to support the use cases that are currently addressed in the documentation. Please reach out with any questions on this work! 

1. A state that demonstrates a progress bar that tracks user progress by percentage. This example would demonstrate a user tracking their own progress through a tutorial or similar use case. 
![image](https://user-images.githubusercontent.com/40275806/46092236-7bb26c00-c182-11e8-8ae4-0db15f554e1b.png)

2. A state that demonstrates to the user a system's progress through downloading a file or application.
![image](https://user-images.githubusercontent.com/40275806/46092507-02674900-c183-11e8-8bcf-2cf4e6a8db7c.png)

3. A state that demonstrates the progress through a series of steps (less than 10). This use case could also be as a user walks through a tutorial.
![image](https://user-images.githubusercontent.com/40275806/46092613-3d697c80-c183-11e8-9fdc-5d89b1bc30ee.png)


4. We will also need a state that represents a time remaining, such as "4 minutes remaining" instead of a percentage. My view is we could just replace this copy in state 1.

**Comment by rachael-phillips** [comment]
Hi! Let me know if this is the wrong place to write this question, and I will take it on over to Slack, but in the process of writing the documentation for progress bars, I've realized that we really do need an animation that demonstrates the difference between indeterminate and determinate progress bars. The documentation I've written covers the differences, but as you can see, only an animation can make this obvious to the user. Can we also provide animated examples for indeterminate and determinate? Here's what that animation looks like: 
![0_amvws1mbig3bpeay](https://user-images.githubusercontent.com/40275806/46099922-23856500-c196-11e8-989b-ceb64c1d8314.gif)

**Comment by mcarrano** [comment]
This is looking good @rachael-phillips I just had a couple of comments that I left in your Google Doc. The examples above look good. Were you thinking that these would be just integrated into the document as static graphics or built as examples in code? We may want to create a demo for this. @LHinson would be interested in your thoughts. Also, @mceledonia and @kybaker please take a look. The step-wise progress indicator is not in the current implementation, so we may need to create a new issue to add this as an enhancement.

As for your question about animations, I think we can include these if they are just animated GIFs like the one attached here. Agree that in some cases these are needed to reflect the design intent.

**Comment by rachael-phillips** [comment]
Hi Matt,

I think our conversation with Kyle this morning will clarify some of this.
I think the progress bar states I've provided need contextual visuals on
the design docs page and examples with code for the examples page. I would
actually narrow the examples we see in the PF-workspace right now and
reorganize the examples to align with the design docs, so that as the user
navigates between examples and design documentation that experience is
consistent. Let's speak more about this, and I'll update here when we are
feeling confident about an idea of what we want to do here.

Thanks!
Rachael

**Comment by rachael-phillips** [comment]
Completed.
