### ISSUE TITLE
PF3 Theme for PF4 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#718]
Demonstrate what a PF3 theme for PF4 components looks like. This demo should illustrate what could be achieved with only modifying PF4 variables and no additional customization. This story also includes providing a recommendation for potential variable to add to PF4, which will allow better alignment with PF3.

**Comment by michael-coker** [comment]
related (w/ design mockup) - https://github.com/patternfly/patternfly-next/issues/421

**Comment by michael-coker** [comment]
Here is as close as I can get to making the PF4 header and navigation look like PF3, using the existing customizable variables in PF4. Note the header is near a 1:1 match, but the navigation is not. https://issue-421-vars--thirsty-noether-30ec26.netlify.com/demos/pagelayout/examples-full/?component=Page%20Layout%20PF-3#

**Comment by michael-coker** [comment]
Here is the PF3 theme demo after adding some additional variables to support a better match to PF3 styles. Aside from a couple of hardcoded styles for the purpose of the demo, all of the PF3 styling is done by simply overwriting CSS variables.

https://issue-421-vars-suggested--thirsty-noether-30ec26.netlify.com/demos/pagelayout/examples-full/?component=Page%20Layout%20PF-3#

**Comment by michael-coker** [comment]
In order to theme PF4 to look as close as possible to the PF3 theme mockup using CSS variables only, I needed to introduce some additional variables into PF4 that didn't exist previously.

There are basically 3 types of additions here. 1 and 2 make sense to me to add, but I'm not sure about 3. 

1. Introduce a **new variable for a property's value that's already in PF4**. The vertical alignment of the text and toggle caret icon in an expandable nav link is a good example. That is current set to `align-items: baseline;`, and since `baseline` is hardcoded in PF4, we can't overwrite/change it with a variable in the PF3 theme. Simply changing that to `align-items: var(--pf-c-nav__list-link--AlignItems);` and setting `--pf-c-nav__list-link--AlignItems` to `baseline` in PF4 allows us to set the value of that variable to something else in the PF3 theme.
   * The only place this wouldn't make sense is when we don't want a user to be able to change the value of a property. In the above example, maybe we always want that value to be `baseline`, because changing it to anything else goes against the design principle of PF3 and PF4.

2. Introduce a **new property and/or variable that is currently unset in PF4, and it makes sense to add so that the user can change it**. The `color` for the toggle caret icon in the vertical navigation is a good example. The color used in PF4 simply relies on inheriting the color from it's ancestor element(s). So here we're adding a new property and variable to the element, but this should be added anyways, should the user wish to change colors used in the navigation component and also wants to change the color of the toggle caret.
   * Again, the only place this wouldn't make sense is when we don't want the user to be able to change this property to a particular value. In the example above, maybe using the color `green` goes against the design principles. 

3. Introduce a **new property and/or variable that is currently not in PF4, for no reason other than to create the PF3 theme**. The horizontal border/line between the top-level navigation elements in the PF3 theme is a good example. The top-level navigation in PF4 does not have a border, so to enable the border in the PF3 theme, we have to add a bunch of border properties and variables to PF4, set them so that they're not visible, then change the border variables in the PF3 theme so that they're visible. This adds a fair amount of bloat to PF4 for something that will never be used in PF4, all so that we can use it in the PF3 theme, with the side benefit (or drawback?) of a user now being able to customize that border, too.

### Page Layout

```
--pf-l-page__header--AlignItems
--pf-l-page__header--wildcard--AlignItems
```
 * be able to adjust vertical alignment of page header elements


### Nav Component

`--pf-c-nav__list-link--AlignItems`
 * to center nav text and toggle icon

`--pf-c-nav__list-link--FontSize`
 * adjust font size of nav links

`--pf-c-nav__list-link--after--Top`
 * be able to adjust top positioning of current nav item's blue border/accent line

```
--pf-c-nav__list-item--BorderBottomWidth
--pf-c-nav__list-item--BorderBottomColor
```
 * border support for nav list items (so I can have a bottom border between top level navigation links)

`--pf-c-nav__list-item--m-current--BackgroundColor`
 * adds a background color for the current nav list item

`--pf-c-nav__simple-list-link--after--Display`
 *  set display property of the blue border for nav links to a var so I can toggle it

```
--pf-c-nav__simple-list-link--FontSize
--pf-c-nav__simple-list-link--LineHeight
```
 * adjust font size of simple-list nav links

`--pf-c-nav__subnav--MarginBottom`
 * add a bottom margin to subnav

`--pf-c-nav__list-toggle--Color`
  * change color of expandable link caret
