### ISSUE TITLE
Progressive Wizard

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-next#755]
Introduce the PF4 progressive wizard

Wireframes are located here: https://redhat.invisionapp.com/share/SZPQWBQY2KH

High Fidelity Mockups: https://redhat.invisionapp.com/share/W3QA5O64XNQ

Contacts:
Ixd: @mcarrano 
Visual designer: @kybaker

**Comment by mcarrano** [comment]
I have been working on a revised approach to the wizard that can work for a variety of use cases that includes both "finite" wizards where the number of steps are known up front or a "progressive" wizard where steps may be revealed as the user progresses through a workflow and decisions are made that may drive subsequent steps in the process. This proposal can be seen in an InVision prototype. Comments welcome.

https://redhat.invisionapp.com/share/SZPQWBQY2KH

**Comment by mcarrano** [comment]
The wireframe level design was reviewed with the UXD leads on Jan 10 and is ready to move for forward to visual design. Updated wireframes can be found here: https://redhat.invisionapp.com/share/SZPQWBQY2KH  These include progress and completion screens that would fall at the end of the flow, after the user clicks "Finish."

**Comment by ajacobs21e** [comment]
I applied Matt's design to my use case (Solution Engine in the Customer Portal) as a PoC. 
https://redhat.invisionapp.com/share/JXPVIIYSN87
I think the biggest differences are I'm not showing steps until the user gets to the point that that step is necessary (in my use case, the user only progresses through the wizard if none of the results match their query) and I have a side panel for additional help & to carry over high priority alerts that were not dismissed in previous steps.

**Comment by andybraren** [comment]
![2019-01-30 10 04 53](https://user-images.githubusercontent.com/9122899/51990175-82c1f180-2476-11e9-9cf4-e34cea3f0f33.png)

@mcarrano Looking at screen 3 of this design (above), would it be acceptable for the user to be able to click between Step 2's substeps in any order? Basically treating those substeps more like clickable subsections rather than a strictly-sequential 2.1, 2.2, 2.3 flow?

Our PF3 application currently uses a wizard with five steps shown across the top of a modal. The fourth step includes a multitude of optional "Advanced" configuration options that some users will need. We currently organize these Advanced options using [collapsible sections](https://www.patternfly.org/pattern-library/forms-and-controls/expand-collapse-section/), but if substeps could behave like subsections we could clean up our UX significantly.

The alternative would be smooshing a vertical column of tabs along the left-hand side of the wizard's content area for that step, but that might look a bit silly.

**Comment by mcarrano** [comment]
@andybraren I think this is a great suggestion. In fact, when I've used sub-steps before, it's exactly how I've wanted to use them. In your scenario, what would you expect the Next button to do? Go to the next substep or skip to the next major step (i.e. Step 3)?

**Comment by andybraren** [comment]
@mcarrano Good question. Hmm.

Thinking aloud:
The user moves to Step 2. All five of Step 2's optional sub-steps are clickable, basically turning them into tab-like subsections of Step 2. The user skims the labels, pokes around in a few of them, decides they don't need to fill in any of the optional things in Step 2, and clicks Next.

I'd say they should see Step 3 no matter which subsection they're currently viewing. Moving to the next subsection (2.2 -> 2.3) would imply that the subsections have a sequential order, which is not the case since they can be clicked in any order. None of the forms in these subsections should be allowed to generate additional subsections either - only major steps (in the rare case that would happen). Step 2's subsections would probably also disappear when moving to Step 3 (unlike your mockup) because they weren't actually "steps" that the user took to arrive at Step 3.

I think that flow checks out and would meet the user's expectations in practice. Does the above sound right to you?

**Comment by mcarrano** [comment]
I agree that the flow you describe makes sense. Also that we would close the substeps when you move on to the next step. Otherwise this lefthand nav could potentially get very long. We haven't written up interaction rules for this yet, but will keep all this in mind as we do.

**Comment by kybaker** [comment]
High fidelity mockups added int he description above - https://redhat.invisionapp.com/share/W3QA5O64XNQ

**Comment by andybraren** [comment]
@mcarrano @kybaker I've been doing some product work that utilizes the latest wizard design. Below is a scenario where the user encounters a bunch of errors within Step 2.

![simple-wizard-status](https://user-images.githubusercontent.com/9122899/52434269-f26e5700-2adc-11e9-8c8a-e016aa7371a9.png)

@matthewcarleton pointed out (and I agree) that it might make sense for the wizard component to visually signify that something went wrong in this step, maybe via a status icon. The above doesn't include substeps/subsections, but the indicator would probably need be consistent in those as well.

Does this seem like something that should be designed for?

**Comment by mcarrano** [comment]
I think that's an interesting idea @andybraren . But before I say yes, let me understand better what the workflow is. I enter step 2 where I can add hosts. What does the Add Host button do here? Is it opening another dialog or adding an entry in the list? How are these errors returned?

**Comment by mcoker** [comment]
Notes from meeting with @kybaker @mcarrano:

* Layout should be header + nav (scrollable) + main area (scrollable) + footer
  * footer should be fixed, so the main area above it scrolls when there is overflow content
  * footer should have modifier to right align buttons (should be left aligned by default)
* In the mobile header:
  * drop the subtitle
  * the height/padding should match the mobile page component header
* Entire top mobile nav area should be clickable, and clicking it toggles the nav menu
* Add a modifier for disabled links in navigation. 
  * remove step number background
  * number and link should use standard disabled color
  * set pointer-events: none;
  * set cursor: disabled;

**Comment by andybraren** [comment]
@mcarrano Here's a recent WIP mockup for some more context:

![simple-wizard-fullpage-context](https://user-images.githubusercontent.com/9122899/52437454-f1412800-2ae4-11e9-9b57-e20df260b6bd.png)

This may look a bit weird because our product is basically a full-page setup wizard, but the same use case would apply to a wizard within a modal. 

Step 2 asks the user to add hosts. They click that "Add Host" button to open a modal which includes a form (IP address/username/password/etc.) that they use to "add" a host to the table. Our product automatically initiates some validation tests of those hosts after they're added, and sometimes those validation tests uncover problems that the user needs to fix before they can continue to Step 3 of our wizard. These errors can sometimes take 60 seconds to be uncovered, so the feedback isn't instant. Another wrench is that our product only requires 3 hosts to be validated successfully before allowing the user to proceed, meaning some hosts could still have errors when they user clicks "Next" and that's okay (but not encouraged).

If we consider the wizard to be a reflection of the user's progress through a complicated multi-step journey, it might make sense to indicate barriers or bumps in the road that the user encounters along that journey. In our case, the wizard would display a little indicator/icon beside Step 2 to remind the user that they didn't quite resolve everything before proceeding to Step 3. Clicking that indicator might display a tooltip to remind the user that there were some non-impeding alerts (of any type) back in that step.

I don't think this is crucial, but it could be a helpful anchor in wizards with many steps and substeps/subsections.

**Comment by mcarrano** [comment]
@andybraren Thanks for the explanation. I think that the flow you describe makes sense and is typical of what often happens in these wizards used for configuring a subsystem of some type. I'd be OK to associate a status or warning with a step. @kybaker can you weight in with the best way to reflect this visually (icon or other method)? I guess another question is whether we need a unique style for this or the user can just add an icon to the step label. Thoughts @mcoker ?

**Comment by mcoker** [comment]
Good point. In the product I work on (fuse online), we have a wizard-type flow (that doesn't use the wizard layout) that does what you're proposing, Andy. We attach an icon to the step to indicate there is some sort of unresolved issue. Clicking the icon gives you a popover with more info. Exhibit A:

<img width="421" alt="screen shot 2019-02-07 at 3 11 24 pm" src="https://user-images.githubusercontent.com/35148959/52443170-a62a1380-2aea-11e9-9a4a-621fb794c392.png">

I think that would be useful. Some thoughts:
* we could add a modifier to the steps for things like "warning" or "danger" that would change the color of things in the step (maybe the background color of the circle under the step # and/or the label text color)
* allow for an icon to be associated with a step that is displayed to the left of the step number(s) that have a warning/error
* just allow users to add an icon at the end of the step label (like @mcarrano suggested)

**Comment by matthewcarleton** [comment]
@mcoker initially when Andy I were talking about it I thought the circle changing colour could be enough. I'd like to hear @kybaker thoughts on it. It seems like the cleanest way to achieve it.

**Comment by katierik** [comment]
Why/when did the wizard switch from having progress buttons on the right (seen in wireframes, more common interaction pattern for wizards) to the buttons on the left (seen in the latest hifi)?

Most examples and implementations of wizards I have seen and researched have the buttons that progress forward on the right.
