### ISSUE TITLE
Implement "more.." action in login demo.

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#801]
Currently the login demo doesn't show what the "more..." option provides b/c we need to hook up JS for the interaction of it. I do think we should create a separate example within that same demo that shows the state of the "more..." action. 

This relates to #785 

Here's the design that shows the "more..." option 
https://drive.google.com/open?id=1Sf5h0rc-ym_8zjA8o11_xbgPWew3bzb3

**Comment by andybraren** [comment]
Some additional comments from @mceledonia about how this should look:

1. Let's keep the padding/margins of all the sections the same as on the login screen. Hopefully that will look alright between the top/header area and the body content.
2. Body section contains 2 columns of icons/labels, 24px spacer between the icon and the label text.
3. Can the footer contain only the back arrow, and have it centered instead of right-aligned as seen here?
4. Let's keep this panel the same height as the login for simplicity.
5. The icons are larger on this screen than the previous panel, here they are 42x42px

**Comment by matthewcarleton** [comment]
closing this as the design has changed to not include this.
