### ISSUE TITLE
Feature Request: Forms with multiple Columns

### ISSUE THREAD

**Issue by TimoSta** [patternfly/patternfly-next#829]
This is a feature request for multi column forms.

A picture is worth a thousand words, so here we go: 

![image](https://user-images.githubusercontent.com/5621996/47241461-bb532900-d3b9-11e8-9dbb-defc39c14d2f.png)

I would like to split a full-width form into multiple columns, on demand, per form group.

This could also work for in-line labels, although it wouldn't look as good in my view:

![image](https://user-images.githubusercontent.com/5621996/47241490-dc1b7e80-d3b9-11e8-87e8-14e7a14dcd77.png)

My use case is to group similar and closely related fields together, more so than it is currently possible with the form group component.

What are your thoughts on this?

**Comment by jgiardino** [comment]
Hi @TimoSta 👋 — great question!

One of the goals with PatternFly 4 is for better modularity. To help achieve this goal, we've tried to decouple our Components from our Layouts, so that components can be assembled using whatever layout the consumer wants to use. And hopefully our Layouts are robust and flexible enough to accommodate any design that someone could imagine.

To test if this system works with the use case you presented, I created a really rough example based on the layout you provided in this [codepen](https://codepen.io/jenngiardino/pen/XxYmJW?editors=1010#). 

I'm copying some of the css developers to review this and just verify that I'm using this system as intended — @michael-coker @matthewcarleton @srambach 

Please let us know if this system satisfies your requirements. 😄

**Comment by TimoSta** [comment]
Hey @jgiardino, thanks so much for putting that example together!

That does work exactly like we need it to, indeed!
