### ISSUE TITLE
VoiceOver and modal/popover issues

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#925]
Related - https://github.com/patternfly/patternfly-next/pull/837

When interacting with a modal that uses both `aria-labelledby` and `aria-describedby`, using VO on chrome, VO will

* read the title
* read the body
* read the footer
* read the body (again)

When interacting with a modal that uses `aria-label` and `aria-describedby`, VO will

* read the contents of `aria-label`
* read the body
* (not read the footer)

cc @jgiardino @matthewcarleton

**Comment by jgiardino** [comment]
The updates included in https://github.com/patternfly/patternfly-react/pull/1052 allow you to edit what attributes are defined within the Modal.

I created different variations of the Modal using `aria-label`, `aria-labelledby`, and `aria-describedby`. In a working Modal, I didn't see any issues with using any of these attributes. I think the weird things we were seeing were a result of seeing a static example of a role that's expected to be dynamic.

I did notice that `role="dialog"` is required for modals to work in NVDA, and that NVDA will announce ALL the contents. Whereas JAWS and VO only announce `aria-label/labelledy`, `aria-describedby` and the element that receives focus. 

I'm closing this issue, since no changes are required for the core implementation.
