### ISSUE TITLE
Restructure Progress Component to work without title/measure elements.

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#961]
Restructure the progress component based on information below:

During the React implementation of the Progress Component this issue was bought to our attention. When the "title" and "measure" elements were removed from the progress component, the spacer between the title and progress bar remained. Its defined by  "--pf-c-progress--GridGap" and is applied to ".pf-c-progress". Right now this means that the progress component cannot exist without the title and measure elements without breaking designs.

@srambach suggests to:
Rather than removing the GridGap, I would manage it by changing the row/column placements. If there is no description and the status is inside or outside - i.e. nothing above the progress bar - then place the progress bar (and if necessary, the status) in the first row withgrid-row: 1/2;
If this is truly a variant, it should probably be implemented in core with a modifier for no description. This wasn't one of the options presented in wireframes or visuals.

This relates to the issue that @tlabaj opened for React https://github.com/patternfly/patternfly-react/issues/946 in React.

**Comment by mcarrano** [comment]
@rachael-phillips created design documentation for Progress Bar so I will defer to her on providing any needed examples.

**Comment by srambach** [comment]
Rather than removing the GridGap, I would manage it by changing the row/column placements. If there is no description and the status is inside or outside - i.e. nothing above the progress bar - then place the progress bar (and if necessary, the status) in the first row with`grid-row: 1/2;`
If this is truly a variant, it should probably be implemented in core with a modifier for no description. This wasn't one of the options presented in wireframes or visuals.

**Comment by christiemolloy** [comment]
That really helps thanks @srambach
