### ISSUE TITLE
Typescript friendly: provide a .d.ts file so typescript-react users can use patternfly 4 too.

### ISSUE THREAD

**Issue by ge0ffrey** [patternfly/patternfly-next#966]
Many programmers coming from a strongly typed language (java, etc) prefer Typescript over JavaScript (for various reasons such as stronger IDE refactoring, fail fastness, etc). For this reason, **all major JavaScript frameworks provide a .d.ts file** so that their API becomes strongly typed for Typescript users. This has no downside for the other JavaScript users.

Patternfly 4 should also provide a .d.ts file.

**Comment by dgutride** [comment]
@ge0ffrey  - patternfly 4 includes no javascript - which typings are you recommended be included in this package?

**Comment by danielefiungo** [comment]
> @ge0ffrey - patternfly 4 includes no javascript - which typings are you recommended be included in this package?

The problem probably belongs to the project patternfly-react, in which we are experiencing the problem  using typescript+react. In order to compile, some kind of workaround is required (like noImplicitAny:false option to the TS compiler)

[see patternfly-react/issues/875](https://github.com/patternfly/patternfly-react/issues/875)

**Comment by dgutride** [comment]
Spoke with team - closing in favor of https://github.com/patternfly/patternfly-react/issues/875
