### ISSUE TITLE
Use a configuration first method (modifiers and states) for ModalBox

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#997]
Relates directly back to #273

**Comment by mcoker** [comment]
After talking with @mcarrano and @kybaker we want to move the close icon closer to the right edge of the modal and aligned to the top of the text in the modal. And the close icon should have it's own "column" in the layout so that text doesn't wrap under it. Similar to this

<img width="710" alt="screen shot 2019-01-03 at 1 09 52 pm" src="https://user-images.githubusercontent.com/35148959/50664845-1685c800-0f74-11e9-808a-051e36d3e412.png">
